-- =======================================================
-- Seeding  'No-Evolution' species table
-- =======================================================
-- Using MERGE and STRUCT for rerun proof list

MERGE `pokemon-corporate-registry.pogo_corp.dim_no_evolution_species` AS target
Using (
    SELECT * FROM UNNEST ([
      STRUCT('Kangaskhan' AS species),
      STRUCT('Pinsir'),
      STRUCT('Tauros'),
      STRUCT('Lapras'),
      STRUCT('Ditto'),
      STRUCT('Aerodactyl'),
      STRUCT('Articuno'),
      STRUCT('Zapdos'),
      STRUCT('Moltres'),
      STRUCT('Mewtwo'),
      STRUCT('Mew'),
      STRUCT('Unown'),
      STRUCT('Shuckle'),
      STRUCT('Heracross'),
      STRUCT('Delibird'),
      STRUCT('Skarmory'),
      STRUCT('Smeargle'),
      STRUCT('Miltank'),
      STRUCT('Raikou'),
      STRUCT('Entei'),
      STRUCT('Suicune'),
      STRUCT('Lugia'),
      STRUCT('Ho-oh'),
      STRUCT('Celebi'),
      STRUCT('Sableye'),
      STRUCT('Mawile'),
      STRUCT('Plusle'),
      STRUCT('Minun'),
      STRUCT('Volbeat'),
      STRUCT('Illumise'),
      STRUCT('Torkoal'),
      STRUCT('Spinda'),
      STRUCT('Zangoose'),
      STRUCT('Seviper'),
      STRUCT('Lunatone'),
      STRUCT('Solrock'),
      STRUCT('Castform'),
      STRUCT('Kecleon'),
      STRUCT('Tropius'),
      STRUCT('Absol'),
      STRUCT('Relicanth'),
      STRUCT('Luvdisc'),
      STRUCT('Regirock'),
      STRUCT('Regice'),
      STRUCT('Registeel'),
      STRUCT('Latias'),
      STRUCT('Latios'),
      STRUCT('Kyogre'),
      STRUCT('Groudon'),
      STRUCT('Rayquaza'),
      STRUCT('Jirachi'),
      STRUCT('Deoxys'),
      STRUCT('Pachirisu'),
      STRUCT('Chatot'),
      STRUCT('Spiritomb'),
      STRUCT('Carnivine'),
      STRUCT('Rotom'),
      STRUCT('Uxie'),
      STRUCT('Mesprit'),
      STRUCT('Azelf'),
      STRUCT('Dialga'),
      STRUCT('Palkia'),
      STRUCT('Heatran'),
      STRUCT('Regigigas'),
      STRUCT('Giratina'),
      STRUCT('Cresselia'),
      STRUCT('Phione'),
      STRUCT('Manaphy'),
      STRUCT('Darkrai'),
      STRUCT('Shaymin'),
      STRUCT('Arceus'),
      STRUCT('Victini'),
      STRUCT('Audino'),
      STRUCT('Throh'),
      STRUCT('Sawk'),
      STRUCT('Maractus'),
      STRUCT('Sigilyph'),
      STRUCT('Emolga'),
      STRUCT('Alomomola'),
      STRUCT('Cryogonal'),
      STRUCT('Stunfisk'),
      STRUCT('Druddigon'),
      STRUCT('Bouffalant'),
      STRUCT('Heatmor'),
      STRUCT('Durant'),
      STRUCT('Cobalion'),
      STRUCT('Terrakion'),
      STRUCT('Virizion'),
      STRUCT('Tornadus'),
      STRUCT('Thundurus'),
      STRUCT('Reshiram'),
      STRUCT('Zekrom'),
      STRUCT('Landorus'),
      STRUCT('Kyurem'),
      STRUCT('Keldeo'),
      STRUCT('Meloetta'),
      STRUCT('Genesect'),
      STRUCT('Furfrou'),
      STRUCT('Hawlucha'),
      STRUCT('Dedenne'),
      STRUCT('Carbink'),
      STRUCT('Klefki'),
      STRUCT('Xerneas'),
      STRUCT('Yveltal'),
      STRUCT('Zygarde'),
      STRUCT('Diancie'),
      STRUCT('Hoopa'),
      STRUCT('Volcanion'),
      STRUCT('Oricorio'),
      STRUCT('Whishiwashi'),
      STRUCT('Comfey'),
      STRUCT('Oranguru'),
      STRUCT('Passimian'),
      STRUCT('Pyukumuku'),
      STRUCT('Minior'),
      STRUCT('Komala'),
      STRUCT('Turtonator'),
      STRUCT('Togedemaru'),
      STRUCT('Mimikyu'),
      STRUCT('Bruxish'),
      STRUCT('Drampa'),
      STRUCT('Dhelmise'),
      STRUCT('Tapu Koko'),
      STRUCT('Tapu Lele'),
      STRUCT('Tapu Bulu'),
      STRUCT('Tapu Fini'),
      STRUCT('Nihilego'),
      STRUCT('Buzzwole'),
      STRUCT('Pheromosa'),
      STRUCT('Xurkitree'),
      STRUCT('Celesteela'),
      STRUCT('Kartana'),
      STRUCT('Guzzlord'),
      STRUCT('Necrozma'),
      STRUCT('Magearna'),
      STRUCT('Marshadow'),
      STRUCT('Stakataka'),
      STRUCT('Blacephalon'),
      STRUCT('Zeraora'),
      STRUCT('Cramorant'),
      STRUCT('Falinks'),
      STRUCT('Pincurchin'),
      STRUCT('Stonjourner'),
      STRUCT('Eiscue'),
      STRUCT('Indeedee'),
      STRUCT('Morpeko'),
      STRUCT('Dracozolt'),
      STRUCT('Arctozolt'),
      STRUCT('Dracovish'),
      STRUCT('Arctovish'),
      STRUCT('Zacian'),
      STRUCT('Zamazenta'),
      STRUCT('Eternatus'),
      STRUCT('Zarude'),
      STRUCT('Regieleki'),
      STRUCT('Regidrago'),
      STRUCT('Glastrier'),
      STRUCT('Spectrier'),
      STRUCT('Calyrex'),
      STRUCT('Enamorus'),
      STRUCT('Squawkabilly'),
      STRUCT('Klawf'),
      STRUCT('Bombirdier'),
      STRUCT('Cyclizar'),
      STRUCT('Orthworm'),
      STRUCT('Flamigo'),
      STRUCT('Veluza'),
      STRUCT('Dondozo'),
      STRUCT('Tatsugiri'),
      STRUCT('Great Tusk'),
      STRUCT('Scream Tail'),
      STRUCT('Brute Bonnet'),
      STRUCT('Flutter Mane'),
      STRUCT('Slither Wing'),
      STRUCT('Sandy Shocks'),
      STRUCT('Iron Treads'),
      STRUCT('Iron Bundle'),
      STRUCT('Iron Hands'),
      STRUCT('Iron Jugulis'),
      STRUCT('Iron Moth'),
      STRUCT('Iron Thorns'),
      STRUCT('Wo-Chien'),
      STRUCT('Chien-Pao'),
      STRUCT('Ting-Lu'),
      STRUCT('Chi-Yu'),
      STRUCT('Roaring Moon'),
      STRUCT('Iron Valiant'),
      STRUCT('Koraidon'),
      STRUCT('Miraidon'),
      STRUCT('Walking Wake'),
      STRUCT('Iron Leaves'),
      STRUCT('Okidogi'),
      STRUCT('Munkidori'),
      STRUCT('Fezandipiti'),
      STRUCT('Ogerpon'),
      STRUCT('Gouging Fire'),
      STRUCT('Raging Bolt'),
      STRUCT('Iron Boulder'),
      STRUCT('Iron Crown'),
      STRUCT('Terapagos'),
      STRUCT('Pecharunt')
    ])
) AS source
ON target.species = source.species

WHEN NOT MATCHED THEN
INSERT (species)
Values (source.species);








