-- ==============================================
-- SEEDING DIM MOVES
-- dps refers to Damage per second
-- ==============================================

MERGE `pokemon-corporate-registry.pogo_corp.dim_moves` target
USING (
  SELECT * FROM UNNEST ([
    --Normal Type
    STRUCT('Tackle' AS move_name, 'Normal' AS move_type, 'fast' AS move_kind, 5 AS damage, 10 AS dps),
    STRUCT('Pound', 'Normal', 'fast', 6, 12),
    STRUCT('Scratch', 'Normal', 'fast', 6, 12),
    STRUCT('Hidden Power', 'Normal', 'fast', 15, 10),
    STRUCT('Cut', 'Normal', 'fast', 5, 10),
    STRUCT('Quick Attack', 'Normal', 'fast', 10, 10),
    STRUCT('Lock-On', 'Normal', 'fast', 2, 4),
    STRUCT('Present', 'Normal', 'fast', 6, 4),
    STRUCT('Take Down', 'Normal', 'fast', 7, 7),
    STRUCT('Yawn', 'Normal', 'fast', 0, 0),
    STRUCT('Body Slam', 'Normal', 'charged', 50, 25),
    STRUCT('Boomburst', 'Normal', 'charged', 150, 60),
    STRUCT('Crush Claw', 'Normal', 'charged', 0, 0),
    STRUCT('Frustration', 'Normal', 'charged', 10, 5),
    STRUCT('Giga Impact', 'Normal', 'charged', 200, 44.4),
    STRUCT('Horn Attack', 'Normal', 'charged', 45, 22.5),
    STRUCT('Horn Drill', 'Normal', 'charged', 9000, 4500),
    STRUCT('Hyper Beam', 'Normal', 'charged', 150, 37.5),
    STRUCT('Hyper Fang', 'Normal', 'charged', 80, 32),
    STRUCT('Last Resort', 'Normal', 'charged', 90, 30),
    STRUCT('Rest', 'Normal', 'charged', 50, 25),
    STRUCT('Return', 'Normal', 'charged', 25, 50),
    STRUCT('Skull Bash', 'Normal', 'charged', 130, 43.3),
    STRUCT('Stomp', 'Normal', 'charged', 50, 33.3),
    STRUCT('Struggle', 'Normal', 'charged', 35, 17.5),
    STRUCT('Swift', 'Normal', 'charged', 65, 21.7),
    STRUCT('Techno Blast', 'Normal', 'charged', 120, 60),
    STRUCT('Transform', 'Normal', 'charged', 0, 0),
    STRUCT('Tri Attack', 'Normal', 'charged', 75, 30),
    STRUCT('Vise Grip', 'Normal', 'charged', 35, 17.5),
    STRUCT('Weather Ball', 'Normal', 'charged', 55, 36.7),
    STRUCT('Wrap', 'Normal', 'charged', 25, 8.3),

    --Fighting Type
    STRUCT('Counter', 'Fighting', 'fast', 13, 13),
    STRUCT('Double Kick', 'Fighting', 'fast', 10, 10),
    STRUCT('Force Palm', 'Fighting', 'fast', 10, 10),
    STRUCT('Karate Chop', 'Fighting', 'fast', 10, 10),
    STRUCT('Low Kick', 'Fighting', 'fast', 5, 10),
    STRUCT('Rock Smash', 'Fighting', 'fast', 17, 11.3),
    STRUCT('Aura Sphere', 'Fighting', 'charged', 100, 50),
    STRUCT('Brick Break', 'Fighting', 'charged', 40, 26.7),
    STRUCT('Close Combat', 'Fighting', 'charged', 105, 42),
    STRUCT('Cross Chop', 'Fighting', 'charged', 50, 33.3),
    STRUCT('Drain Punch', 'Fighting', 'charged', 50, 20),
    STRUCT('Dynamic Punch', 'Fighting', 'charged', 85, 34),
    STRUCT('Flying Press', 'Fighting', 'charged', 115, 46),
    STRUCT('Focus Blast', 'Fighting', 'charged', 140, 40),
    STRUCT('High Jump Kick', 'Fighting', 'charged', 90, 60),
    STRUCT('Low Sweep', 'Fighting', 'charged', 40, 20),
    STRUCT('Power-Up Punch', 'Fighting', 'charged', 50, 25),
    STRUCT('Sacred Sword', 'Fighting', 'charged', 50, 50),
    STRUCT('Submission', 'Fighting', 'charged', 55, 27.5),
    STRUCT('Superpower', 'Fighting', 'charged', 85, 28.3),
    STRUCT('Upper Hand', 'Fighting', 'charged', 50, 25),

    --Flying Type
    STRUCT('Air Slash', 'Flying', 'fast', 12, 12),
    STRUCT('Gust', 'Flying', 'fast', 25, 12.5),
    STRUCT('Peck', 'Flying', 'fast', 10, 10),
    STRUCT('Wing Attack', 'Flying', 'fast', 10, 10),
    STRUCT('Acrobatics', 'Flying', 'charged', 100, 50),
    STRUCT('Aerial Ace', 'Flying', 'charged', 55, 22),
    STRUCT('Aeroblast', 'Flying', 'charged', 180, 51),
    STRUCT('Aeroblast+', 'Flying', 'charged', 200, 57),
    STRUCT('Aeroblast++', 'Flying', 'charged', 225, 64),
    STRUCT('Air Cutter', 'Flying', 'charged', 55, 22),
    STRUCT('Bleakwind Storm', 'Flying', 'charged', 150, 60),
    STRUCT('Brave Bird', 'Flying', 'charged', 130, 65),
    STRUCT('Dragon Ascent', 'Flying', 'charged', 140, 40),
    STRUCT('Drill Peck', 'Flying', 'charged', 70, 28),
    STRUCT('Feather Dance', 'Flying', 'charged', 35, 11.7),
    STRUCT('Fly', 'Flying', 'charged', 90, 45),
    STRUCT('Hurricane', 'Flying', 'charged', 105, 42),
    STRUCT('Oblivion Wing', 'Flying', 'charged', 85, 42.5),
    STRUCT('Sky Attack', 'Flying', 'charged', 80, 40),

    --Poison Type
    STRUCT('Acid', 'Poison', 'fast', 11, 11),
    STRUCT('Poison Jab', 'Poison', 'fast', 13, 13),
    STRUCT('Poison Sting', 'Poison', 'fast', 4, 8),
    STRUCT('Acid Spray', 'Poison', 'charged', 20, 6.7),
    STRUCT('Cross Poison', 'Poison', 'charged', 40, 26.7),
    STRUCT('Gunk Shot', 'Poison', 'charged', 130, 43.3),
    STRUCT('Poison Fang', 'Poison', 'charged', 30, 20),
    STRUCT('Sludge', 'Poison', 'charged', 50, 25),
    STRUCT('Sludge Bomb', 'Poison', 'charged', 85, 34),
    STRUCT('Sludge Wave', 'Poison', 'charged', 105, 35),

    --Ground Type
    STRUCT('Mud Shot', 'Ground', 'fast', 4, 8),
    STRUCT('Mud-Slap', 'Ground', 'fast', 19, 12.7),
    STRUCT('Sand Attack', 'Ground', 'fast', 4, 8),
    STRUCT('Bone Club', 'Ground', 'charged', 40, 26.7),
    STRUCT('Bulldoze', 'Ground', 'charged', 80, 22.9),
    STRUCT('Dig', 'Ground', 'charged', 100, 22.2),
    STRUCT('Drill Run', 'Ground', 'charged', 85, 28.3),
    STRUCT('Earth Power', 'Ground', 'charged', 100, 28.6),
    STRUCT('Earthquake', 'Ground', 'charged', 140, 40),
    STRUCT('Fissure', 'Ground', 'charged', 9001, 3000),
    STRUCT('High Horsepower', 'Ground', 'charged', 105, 70),
    STRUCT('Mud Bomb', 'Ground', 'charged', 60, 24),
    STRUCT('Precipice Blades', 'Ground', 'charged', 120, 80),
    STRUCT('Sand Tomb', 'Ground', 'charged', 60, 15),
    STRUCT('Sandsear Storm', 'Ground', 'charged', 150, 60),
    STRUCT('Scorching Sands', 'Ground', 'charged', 90, 30),

    --Rock Type
    STRUCT('Rock Throw', 'Rock', 'fast', 13, 13),
    STRUCT('Rollout', 'Rock', 'fast', 15, 10),
    STRUCT('Smack Down', 'Rock', 'fast', 13, 13),
    STRUCT('Ancient Power', 'Rock', 'charged', 70, 20),
    STRUCT('Meteor Beam', 'Rock', 'charged', 140, 70),
    STRUCT('Power Gem', 'Rock', 'charged', 80, 26.7),
    STRUCT('Rock Blast', 'Rock', 'charged', 50, 25), 
    STRUCT('Rock Slide', 'Rock', 'charged', 75, 30),
    STRUCT('Rock Tomb', 'Rock', 'charged', 65, 21.7),
    STRUCT('Rock Wrecker', 'Rock', 'charged', 110, 31.4),
    STRUCT('Stone Edge', 'Rock', 'charged', 105, 42),
    STRUCT('Weather Ball', 'Rock', 'charged', 55, 36.7),

    --Bug Type
    STRUCT('Bug Bite', 'Bug', 'fast', 5, 10),
    STRUCT('Fury Cutter', 'Bug', 'fast', 4, 8),
    STRUCT('Infestation', 'Bug', 'fast', 9, 9),
    STRUCT('Struggle Bug', 'Bug', 'fast', 15, 10),
    STRUCT('Bug Buzz', 'Bug', 'charged', 95, 27.1),
    STRUCT('Fell Stinger', 'Bug', 'charged', 45, 22.5),
    STRUCT('Leech Life', 'Bug', 'charged', 0, 0),
    STRUCT('Lunge', 'Bug', 'charged', 55, 18.3),
    STRUCT('Megahorn', 'Bug', 'charged', 105, 53),
    STRUCT('Signal Beam', 'Bug', 'charged', 75, 25),
    STRUCT('Silver Wind', 'Bug', 'charged', 65, 18.6),
    STRUCT('X-Scissor', 'Bug', 'charged', 45, 30),

    --Ghost Type
    STRUCT('Astonish', 'Ghost', 'fast', 7, 7),
    STRUCT('Hex', 'Ghost', 'fast', 8, 8),
    STRUCT('Lick', 'Ghost', 'fast', 5, 10),
    STRUCT('Shadow Claw', 'Ghost', 'fast', 6, 12),
    STRUCT('Moongeist Beam', 'Ghost', 'charged', 230, 77),
    STRUCT('Night Shade', 'Ghost', 'charged', 60, 24),
    STRUCT('Ominous Wind', 'Ghost', 'charged', 55, 22),
    STRUCT('Poltergeist', 'Ghost', 'charged', 140, 40),
    STRUCT('Rage Fist', 'Ghost', 'charged', 100, 33.3),
    STRUCT('Shadow Ball', 'Ghost', 'charged', 100, 33.3),
    STRUCT('Shadow Bone', 'Ghost', 'charged', 85, 28.3),
    STRUCT('Shadow Force', 'Ghost', 'charged', 140, 70),
    STRUCT('Shadow Punch', 'Ghost', 'charged', 35, 23.3),
    STRUCT('Shadow Sneak', 'Ghost', 'charged', 50, 16.7),
    STRUCT('Spirit Shackle', 'Ghost', 'charged', 70, 28),

    --Steel Type
    STRUCT('Bullet Punch', 'Steel', 'fast', 10, 10),
    STRUCT('Iron Tail', 'Steel', 'fast', 14, 14),
    STRUCT('Metal Claw', 'Steel', 'fast', 6, 12),
    STRUCT('Metal Sound', 'Steel', 'fast', 4, 8),
    STRUCT('Steel Wing', 'Steel', 'fast', 14, 14),
    STRUCT('Behemoth Bash', 'Steel', 'charged', 1, 0.7),
    STRUCT('Behemoth Blade', 'Steel', 'charged', 1, 0.3),
    STRUCT('Doom Desire', 'Steel', 'charged', 65, 43.3),
    STRUCT('Double Iron Bash', 'Steel', 'charged', 70, 35),
    STRUCT('Flash Cannon', 'Steel', 'charged', 100, 40),
    STRUCT('Gyro Ball', 'Steel', 'charged', 85, 24.3),
    STRUCT('Heavy Slam', 'Steel', 'charged', 70, 35),
    STRUCT('Iron Head', 'Steel', 'charged', 60, 30),
    STRUCT('Magnet Bomb', 'Steel', 'charged', 75, 25),
    STRUCT('Meteor Mash', 'Steel', 'charged', 100, 40),
    STRUCT('Mirror Shot', 'Steel', 'charged', 50, 20),
    STRUCT('Sunsteel Strike', 'Steel', 'charged', 230, 77),

    --Fire Type
    STRUCT('Ember', 'Fire', 'fast', 10, 10),
    STRUCT('Fire Fang', 'Fire', 'fast', 13, 13),
    STRUCT('Fire Spin', 'Fire', 'fast', 13, 13),
    STRUCT('Incinerate', 'Fire', 'fast', 32, 12.8),
    STRUCT('Blast Burn', 'Fire', 'charged', 120, 34.3),
    STRUCT('Blaze Kick', 'Fire', 'charged', 40, 40),
    STRUCT('Fire Blast', 'Fire', 'charged', 140, 35),
    STRUCT('Fire Punch', 'Fire', 'charged', 50, 25),
    STRUCT('Flame Burst', 'Fire', 'charged', 70, 28),
    STRUCT('Flame Charge', 'Fire', 'charged', 70, 17.5),
    STRUCT('Flame Wheel', 'Fire', 'charged', 55, 22),
    STRUCT('Flamethrower', 'Fire', 'charged', 65, 32.5),
    STRUCT('Fusion Flare', 'Fire', 'charged', 140, 70),
    STRUCT('Heat Wave', 'Fire', 'charged', 95, 31.7),
    STRUCT('Magma Storm', 'Fire', 'charged', 75, 30),
    STRUCT('Mystical Fire', 'Fire', 'charged', 60, 30),
    STRUCT('Overheat', 'Fire', 'charged', 160, 40),
    STRUCT('Sacred Fire', 'Fire', 'charged', 120, 48),
    STRUCT('Sacred Fire+', 'Fire', 'charged', 135, 54),
    STRUCT('Sacred Fire ++', 'Fire', 'charged', 155, 62),
    STRUCT('Techno Blast', 'Fire', 'charged', 120, 60),
    STRUCT('Torch Song', 'Fire', 'charged', 100, 28.6),
    STRUCT('V-Create', 'Fire', 'charged', 105, 35),
    STRUCT('Weather Ball', 'Fire', 'charged', 55, 36.7),

    --Water Type
    STRUCT('Bubble', 'Water', 'fast', 10, 10),
    STRUCT('Splash', 'Water', 'fast', 0, 0),
    STRUCT('Water Gun', 'Water', 'fast', 5, 10),
    STRUCT('Water Gun+', 'Water', 'fast', 10, 10),
    STRUCT('Water Shuriken', 'Water', 'fast', 9, 9),
    STRUCT('Waterfall', 'Water', 'fast', 13, 13),
    STRUCT('Aqua Jet', 'Water', 'charged', 45, 18),
    STRUCT('Aqua Tail', 'Water', 'charged', 50, 25),
    STRUCT('Brine', 'Water', 'charged', 65, 26),
    STRUCT('Bubble Beam', 'Water', 'charged', 45, 22.5),
    STRUCT('Crabhammer', 'Water', 'charged', 85, 42.5),
    STRUCT('Hydro Cannon', 'Water', 'charged', 90, 45),
    STRUCT('Hydro Pump', 'Water', 'charged', 90, 20),
    STRUCT('Hydro Pump+', 'Water', 'charged', 135, 38.6),
    STRUCT('Liquidation', 'Water', 'charged', 70, 23.3),
    STRUCT('Muddy Water', 'Water', 'charged', 45, 22.5),
    STRUCT('Octazooka', 'Water', 'charged', 55, 22),
    STRUCT('Origin Pulse', 'Water', 'charged', 120, 80),
    STRUCT('Razor Shell', 'Water', 'charged', 55, 36.7),
    STRUCT('Scald', 'Water', 'charged', 50, 11.1),
    STRUCT('Scald+', 'Water', 'charged', 75, 21.4),
    STRUCT('Sparkling Aria', 'Water', 'charged', 85, 28.3),
    STRUCT('Surf', 'Water', 'charged', 60, 40),
    STRUCT('Techno Blast', 'Water', 'charged', 120, 60),
    STRUCT('Water Pulse', 'Water', 'charged', 65, 21.7),
    STRUCT('Weather Ball', 'Water', 'charged', 55, 36.7),

    --Grass Type
    STRUCT('Bullet Seed', 'Grass', 'fast', 7, 7),
    STRUCT('Leafage', 'Grass', 'fast', 6, 12),
    STRUCT('Magical Leaf', 'Grass', 'fast', 17, 11.3),
    STRUCT('Razor Leaf', 'Grass', 'fast', 13, 13),
    STRUCT('Vine Whip', 'Grass', 'fast', 6, 12),
    STRUCT('Energy Ball', 'Grass', 'charged', 90, 22.5),
    STRUCT('Flower Trick', 'Grass', 'charged', 75, 27.8),
    STRUCT('Frenzy Plant', 'Grass', 'charged', 100, 40),
    STRUCT('Giga Drain', 'Grass', 'charged', 50, 12.5),
    STRUCT('Grass Knot', 'Grass', 'charged', 90, 36),
    STRUCT('Leaf Blade', 'Grass', 'charged', 70, 28),
    STRUCT('Leaf Storm', 'Grass', 'charged', 130, 52),
    STRUCT('Leaf Tornado', 'Grass', 'charged', 45, 15),
    STRUCT('Mega Drain', 'Grass', 'charged', 25, 10),
    STRUCT('Petal Blizzard', 'Grass', 'charged', 110, 44),
    STRUCT('Power Whip', 'Grass', 'charged', 90, 36),
    STRUCT('Seed Bomb', 'Grass', 'charged', 55, 27.5),
    STRUCT('Seed Flare', 'Grass', 'charged', 115, 46),
    STRUCT('Solar Beam', 'Grass', 'charged', 180, 36),
    STRUCT('Trailblaze', 'Grass', 'charged', 65, 32.5),

    -- Electric Type
    STRUCT('Charge Beam', 'Electric', 'fast', 7, 7),
    STRUCT('Spark', 'Electric', 'fast', 4, 8),
    STRUCT('Thunder Fang', 'Electric', 'fast', 10, 10),
    STRUCT('Thunder Shock', 'Electric', 'fast', 4, 8),
    STRUCT('Volt Switch', 'Electric', 'fast', 13, 8.7),
    STRUCT('Aura Wheel', 'Electric', 'charged', 100, 37),
    STRUCT('Discharge', 'Electric', 'charged', 65, 26),
    STRUCT('Fusion Bolt', 'Electric', 'charged', 140, 70),
    STRUCT('Parabolic Charge', 'Electric', 'charged', 70, 23.3),
    STRUCT('Techno Blast', 'Electric', 'charged', 120, 60),
    STRUCT('Thunder', 'Electric', 'charged', 100, 40),
    STRUCT('Thunder Punch', 'Electric', 'charged', 50, 25),
    STRUCT('Thunderbolt', 'Electric', 'charged', 80, 32),
    STRUCT('Volt Tackle', 'Electric', 'charged', 90, 25.7),
    STRUCT('Wild Charge', 'Electric', 'charged', 90, 36),
    STRUCT('Wildbolt Storm', 'Electric', 'charged', 150, 60),
    STRUCT('Zap Cannon', 'Electric', 'charged', 140, 40),

    --Psychic Type
    STRUCT('Confusion', 'Psychic', 'fast', 19, 12.7),
    STRUCT('Extrasensory', 'Psychic', 'fast', 11, 11),
    STRUCT('Psycho Cut', 'Psychic', 'fast', 4, 8),
    STRUCT('Psywave', 'Psychic', 'fast', 4, 8),
    STRUCT('Zen Headbutt', 'Psychic', 'fast', 11, 11),
    STRUCT('Future Sight', 'Psychic', 'charged', 115, 46),
    STRUCT('Heart Stamp', 'Psychic', 'charged', 40, 20),
    STRUCT('Luster Purge', 'Psychic', 'charged', 100, 67),
    STRUCT('Mirror Coat', 'Psychic', 'charged', 60, 24),
    STRUCT('Mist Ball', 'Psychic', 'charged', 105, 53),
    STRUCT('Psybeam', 'Psychic', 'charged', 65, 21.7),
    STRUCT('Psychic', 'Psychic', 'charged', 95, 31.7),
    STRUCT('Psychic Fangs', 'Psychic', 'charged', 25, 25),
    STRUCT('Psycho Boost', 'Psychic', 'charged', 70, 17.5),
    STRUCT('Psyshock', 'Psychic', 'charged', 60, 24),
    STRUCT('Psystrike', 'Psychic', 'charged', 95, 38),
    STRUCT('Synchronoise', 'Psychic', 'charged', 80, 32),

    --Ice Type
    STRUCT('Frost Breath', 'Ice', 'fast', 11, 11),
    STRUCT('Ice Fang', 'Ice', 'fast', 12, 8),
    STRUCT('Ice Shard', 'Ice', 'fast', 10, 10),
    STRUCT('Powder Snow', 'Ice', 'fast', 6, 6),
    STRUCT('Aurora Beam', 'Ice', 'charged', 80, 22.9),
    STRUCT('Avalanche', 'Ice', 'charged', 85, 34),
    STRUCT('Blizzard', 'Ice', 'charged', 130, 43.3),
    STRUCT('Freeze Shock', 'Ice', 'charged', 160, 107),
    STRUCT('Glaciate', 'Ice', 'charged', 160, 64),
    STRUCT('Ice Beam', 'Ice', 'charged', 95, 27.1),
    STRUCT('Ice Burn', 'Ice', 'charged', 90, 45),
    STRUCT('Ice Punch', 'Ice', 'charged', 50, 25),
    STRUCT('Icy Wind', 'Ice', 'charged', 65, 18.6),
    STRUCT('Techno Blast', 'Ice', 'charged', 120, 60),
    STRUCT('Triple Axel', 'Ice', 'charged', 60, 30),
    STRUCT('Weather Ball', 'Ice', 'charged', 55, 36.7),

    --Dragon Type
    STRUCT('Dragon Breath', 'Dragon', 'fast', 6, 12),
    STRUCT('Dragon Tail', 'Dragon', 'fast', 14, 14),
    STRUCT('Breaking Swipe', 'Dragon', 'charged', 45, 45),
    STRUCT('Draco Meteor', 'Dragon', 'charged', 123, 123),
    STRUCT('Dragon Claw', 'Dragon', 'charged', 45, 30),
    STRUCT('Dragon Pulse', 'Dragon', 'charged', 90, 25.7),
    STRUCT('Outrage', 'Dragon', 'charged', 110, 27.5),
    STRUCT('Roar of Time', 'Dragon', 'charged', 160, 80),
    STRUCT('Spacial Rend', 'Dragon', 'charged', 160, 64),
    STRUCT('Twister', 'Dragon', 'charged', 50, 16.7),

    --Dark Type
    STRUCT('Bite', 'Dark', 'fast', 6, 12),
    STRUCT('Feint Attack', 'Dark', 'fast', 11, 11),
    STRUCT('Snarl', 'Dark', 'fast', 11, 11),
    STRUCT('Sucker Punch', 'Dark', 'fast', 5, 10),
    STRUCT('Aura Wheel', 'Dark', 'charged', 100, 37),
    STRUCT('Brutal Swing', 'Dark', 'charged', 65, 32.5),
    STRUCT('Crunch', 'Dark', 'charged', 65, 21.7),
    STRUCT('Dark Pulse', 'Dark', 'charged', 80, 26.7),
    STRUCT('Darkest Lariat', 'Dark', 'charged', 80, 40),
    STRUCT('Foul Play', 'Dark', 'charged', 70, 35),
    STRUCT('Night Slash', 'Dark', 'charged', 45, 22.5),
    STRUCT('Obstruct', 'Dark', 'charged', 20, 13.3),
    STRUCT('Payback', 'Dark', 'charged', 95, 47.5),

    --Fairy Type
    STRUCT('Charm', 'Fairy', 'fast', 20, 13.3),
    STRUCT('Fairy Wind', 'Fairy', 'fast', 9, 9),
    STRUCT('Geomancy', 'Fairy', 'fast', 20, 13.3),
    STRUCT('Dazzling Gleam', 'Fairy', 'charged', 100, 28.6),
    STRUCT('Disarming Voice', 'Fairy', 'charged', 70, 17.5),
    STRUCT('Draining Kiss', 'Fairy', 'charged', 60, 24),
    STRUCT('Moonblast', 'Fairy', 'charged', 130, 32.5),
    STRUCT("Nature's Madness", 'Fairy', 'charged', 90, 45),
    STRUCT('Play Rough', 'Fairy', 'charged', 90, 30)

  ])
) AS source
ON target.move_name = source.move_name
WHEN NOT MATCHED THEN
  INSERT (move_name, move_type, move_kind, damage, dps)
  VALUES (source.move_name, source.move_type, source.move_kind, source.damage, source.dps);


















