-- =============================================
-- SEEDING DIM SPECIES LIST
-- Kanto, Johto, Hoenn Regions
-- =============================================

MERGE `pokemon-corporate-registry.pogo_corp.dim_species` target
USING ( 
  SELECT * FROM UNNEST ([
    --Kanto Region
    STRUCT(0001 AS pokedex_number, 'Kanto' AS pokemon_region, 'Bulbasaur' AS pokemon_species, 'Grass' AS primary_type, 'Poison' AS secondary_type),
    STRUCT(0002, 'Kanto', 'Ivysaur', 'Grass' , 'Poison'),
    STRUCT(0003, 'Kanto', 'Venusaur', 'Grass' , 'Poison'),
    STRUCT(0004, 'Kanto', 'Charmander', 'Fire' , NULL),
    STRUCT(0005, 'Kanto', 'Charmeleon', 'Fire' , NULL),
    STRUCT(0006, 'Kanto', 'Charizard', 'Fire' , 'Flying'),
    STRUCT(0007, 'Kanto', 'Squirtle', 'Water' , NULL),
    STRUCT(0008, 'Kanto', 'Wartortle', 'Water' , NULL),
    STRUCT(0009, 'Kanto', 'Blastoise', 'Water' , NULL),

    STRUCT(0010, 'Kanto', 'Caterpie', 'Bug' , NULL),
    STRUCT(0011, 'Kanto', 'Metapod', 'Bug' , NULL),
    STRUCT(0012, 'Kanto', 'Butterfree', 'Bug' , 'Flying'),
    STRUCT(0013, 'Kanto', 'Weedle', 'Bug' , 'Poison'),
    STRUCT(0014, 'Kanto', 'Kakuna', 'Bug' , 'Poison'),
    STRUCT(0015, 'Kanto', 'Beedrill', 'Bug' , 'Poison'),
    STRUCT(0016, 'Kanto', 'Pidgey', 'Normal' , 'Flying'),
    STRUCT(0017, 'Kanto', 'Pidgeotto', 'Normal' , 'Flying'),
    STRUCT(0018, 'Kanto', 'Pidgeot', 'Normal' , 'Flying'),
    STRUCT(0019, 'Kanto', 'Rattata', 'Normal' , NULL),

    STRUCT(0020, 'Kanto', 'Raticate', 'Normal' , NULL),
    STRUCT(0021, 'Kanto', 'Spearow', 'Normal' , 'Flying'),
    STRUCT(0022, 'Kanto', 'Fearow', 'Normal' , 'Flying'),
    STRUCT(0023, 'Kanto', 'Ekans', 'Poison' , NULL),
    STRUCT(0024, 'Kanto', 'Arbok', 'Poison' , NULL),
    STRUCT(0025, 'Kanto', 'Pikachu', 'Electric' , NULL),
    STRUCT(0026, 'Kanto', 'Raichu', 'Electric' , NULL),
    STRUCT(0027, 'Kanto', 'Sandshrew', 'Ground' , NULL),
    STRUCT(0028, 'Kanto', 'Sandslash', 'Ground' , NULL),
    STRUCT(0029, 'Kanto', 'NidoranF', 'Poison' , NULL),

    STRUCT(0030, 'Kanto', 'Nidorina', 'Poison' , NULL),
    STRUCT(0031, 'Kanto', 'Nidoqueen', 'Poison' , 'Ground'),
    STRUCT(0032, 'Kanto', 'NidoranM', 'Poison' , NULL),
    STRUCT(0033, 'Kanto', 'Nidorino', 'Poison' , NULL),
    STRUCT(0034, 'Kanto', 'Nidoking', 'Poison' , 'Ground'),
    STRUCT(0035, 'Kanto', 'Clefairy', 'Fairy' , NULL),
    STRUCT(0036, 'Kanto', 'Clefable', 'Fairy' , NULL),
    STRUCT(0037, 'Kanto', 'Vulpix', 'Fire' , NULL),
    STRUCT(0038, 'Kanto', 'Ninetales', 'Fire' , NULL),
    STRUCT(0039, 'Kanto', 'Jigglypuff', 'Normal' , 'Fairy'),

    STRUCT(0040, 'Kanto', 'Wigglytuff', 'Normal' , 'Fairy'),
    STRUCT(0041, 'Kanto', 'Zubat', 'Poison' , 'Flying'),
    STRUCT(0042, 'Kanto', 'Golbat', 'Poison' , 'Flying'),
    STRUCT(0043, 'Kanto', 'Oddish', 'Grass' , 'Poison'),
    STRUCT(0044, 'Kanto', 'Gloom', 'Grass' , 'Poison'),
    STRUCT(0046, 'Kanto', 'Paras', 'Bug' , 'Grass'),
    STRUCT(0047, 'Kanto', 'Parasect', 'Bug' , 'Grass'),
    STRUCT(0048, 'Kanto', 'Venonat', 'Bug' , 'Poison'),
    STRUCT(0049, 'Kanto', 'Venomoth', 'Bug' , 'Poison'),

    STRUCT(0050, 'Kanto', 'Diglett', 'Ground' , NULL),
    STRUCT(0051, 'Kanto', 'Dugtrio', 'Ground' , NULL),
    STRUCT(0052, 'Kanto', 'Meowth', 'Normal' , NULL),
    STRUCT(0053, 'Kanto', 'Persian', 'Normal' , NULL),
    STRUCT(0054, 'Kanto', 'Psyduck', 'Water' , NULL),
    STRUCT(0055, 'Kanto', 'Golduck', 'Water' , NULL),
    STRUCT(0056, 'Kanto', 'Mankey', 'Fighting' , NULL),
    STRUCT(0057, 'Kanto', 'Primeape', 'Fighting' , NULL),
    STRUCT(0058, 'Kanto', 'Growlithe', 'Fire' , NULL),
    STRUCT(0059, 'Kanto', 'Arcanine', 'Fire' , NULL),

    STRUCT(0060, 'Kanto', 'Poliwag', 'Water' , NULL),
    STRUCT(0061, 'Kanto', 'Poliwhirl', 'Water' , NULL),
    STRUCT(0062, 'Kanto', 'Poliwrath', 'Water' , 'Fighting'),
    STRUCT(0063, 'Kanto', 'Abra', 'Psychic' , NULL),
    STRUCT(0064, 'Kanto', 'Kadabra', 'Psychic' , NULL),
    STRUCT(0065, 'Kanto', 'Alakazam', 'Psychic' , NULL),
    STRUCT(0066, 'Kanto', 'Machop', 'Fighting' , NULL),
    STRUCT(0067, 'Kanto', 'Machoke', 'Fighting' , NULL),
    STRUCT(0068, 'Kanto', 'Machamp', 'Fighting' , NULL),
    STRUCT(0069, 'Kanto', 'Bellsprout', 'Grass' , 'Poison'),

    STRUCT(0070, 'Kanto', 'Weepinbell', 'Grass' , 'Poison'),
    STRUCT(0071, 'Kanto', 'Victreebel', 'Grass' , 'Poison'),
    STRUCT(0072, 'Kanto', 'Tentacool', 'Water' , 'Poison'),
    STRUCT(0073, 'Kanto', 'Tentacruel', 'Water' , 'Poison'),
    STRUCT(0074, 'Kanto', 'Geodude', 'Rock' , 'Ground'),
    STRUCT(0075, 'Kanto', 'Graveler', 'Rock' , 'Ground'),
    STRUCT(0076, 'Kanto', 'Golem', 'Rock' , 'Ground'),
    STRUCT(0077, 'Kanto', 'Ponyta', 'Fire' , NULL),
    STRUCT(0078, 'Kanto', 'Rapidash', 'Fire' , NULL),
    STRUCT(0079, 'Kanto', 'Slowpoke', 'Water' , 'Psychic'),

    STRUCT(0080, 'Kanto', 'Slowbro', 'Water' , 'Psychic'),
    STRUCT(0081, 'Kanto', 'Magnemite', 'Electric' , 'Steel'),
    STRUCT(0082, 'Kanto', 'Magneton', 'Electric' , 'Steel'),
    STRUCT(0083, 'Kanto', "Farfetch'd", 'Normal' , 'Flying'),
    STRUCT(0084, 'Kanto', 'Doduo', 'Normal' , 'Flying'),
    STRUCT(0085, 'Kanto', 'Dodrio', 'Normal' , 'Flying'),
    STRUCT(0086, 'Kanto', 'Seel', 'Water' , NULL),
    STRUCT(0087, 'Kanto', 'Dewgong', 'Water' , 'Ice'),
    STRUCT(0088, 'Kanto', 'Grimer', 'Poison' , NULL),
    STRUCT(0089, 'Kanto', 'Muk', 'Poison' , NULL),

    STRUCT(0090, 'Kanto', 'Shellder', 'Water' , NULL),
    STRUCT(0091, 'Kanto', 'Cloyster', 'Water' , 'Ice'),
    STRUCT(0092, 'Kanto', 'Gastly', 'Ghost' , 'Poison'),
    STRUCT(0093, 'Kanto', 'Haunter', 'Ghost' , 'Poison'),
    STRUCT(0094, 'Kanto', 'Gengar', 'Ghost' , 'Poison'),
    STRUCT(0095, 'Kanto', 'Onix', 'Rock' , 'Ground'),
    STRUCT(0096, 'Kanto', 'Drowzee', 'Psychic' , NULL),
    STRUCT(0097, 'Kanto', 'Hypno', 'Psychic' , NULL),
    STRUCT(0098, 'Kanto', 'Krabby', 'Water' , NULL),
    STRUCT(0099, 'Kanto', 'Kingler', 'Water' , NULL),

    STRUCT(0100, 'Kanto', 'Voltorb', 'Electric' , NULL),
    STRUCT(0101, 'Kanto', 'Electrode', 'Electric' , NULL),
    STRUCT(0102, 'Kanto', 'Exeggcute', 'Grass' , 'Psychic'),
    STRUCT(0103, 'Kanto', 'Exeggutor', 'Grass' , 'Psychic'),
    STRUCT(0104, 'Kanto', 'Cubone', 'Ground' , NULL),
    STRUCT(0105, 'Kanto', 'Marowak', 'Ground' , NULL),
    STRUCT(0106, 'Kanto', 'Hitmonlee', 'Fighting' , NULL),
    STRUCT(0107, 'Kanto', 'Hitmonchan', 'Fighting' , NULL),
    STRUCT(0108, 'Kanto', 'Lickitung', 'Normal' , NULL),
    STRUCT(0109, 'Kanto', 'Koffing', 'Poison' , NULL),

    STRUCT(0110, 'Kanto', 'Weezing', 'Poison' , NULL),
    STRUCT(0111, 'Kanto', 'Rhyhorn', 'Ground' , 'Rock'),
    STRUCT(0112, 'Kanto', 'Rhydon', 'Ground' , 'Rock'),
    STRUCT(0113, 'Kanto', 'Chansey', 'Normal' , NULL),
    STRUCT(0114, 'Kanto', 'Tangela', 'Grass' , NULL),
    STRUCT(0115, 'Kanto', 'Kangaskhan', 'Normal' , NULL),
    STRUCT(0116, 'Kanto', 'Horsea', 'Water' , NULL),
    STRUCT(0117, 'Kanto', 'Seadra', 'Water' , NULL),
    STRUCT(0118, 'Kanto', 'Goldeen', 'Water' , NULL),
    STRUCT(0119, 'Kanto', 'Seaking', 'Water' , NULL),

    STRUCT(0120, 'Kanto', 'Staryu', 'Water' , NULL),
    STRUCT(0121, 'Kanto', 'Starmie', 'Water' , NULL),
    STRUCT(0122, 'Kanto', 'Mr.Mime', 'Psychic' , 'Fairy'),
    STRUCT(0123, 'Kanto', 'Scyther', 'Bug' , 'Flying'),
    STRUCT(0124, 'Kanto', 'Jynx', 'Ice' , 'Psychic'),
    STRUCT(0125, 'Kanto', 'Electabuzz', 'Electric' , NULL),
    STRUCT(0126, 'Kanto', 'Magmar', 'Fire' , NULL),
    STRUCT(0127, 'Kanto', 'Pinsir', 'Bug' , NULL),
    STRUCT(0128, 'Kanto', 'Tauros', 'Normal' , NULL),
    STRUCT(0129, 'Kanto', 'Magikarp', 'Water' , NULL),

    STRUCT(0130, 'Kanto', 'Gyarados', 'Water' , 'Flying'),
    STRUCT(0131, 'Kanto', 'Lapras', 'Water' , 'Ice'),
    STRUCT(0132, 'Kanto', 'Ditto', 'Normal' , NULL),
    STRUCT(0133, 'Kanto', 'Eevee', 'Normal' , NULL),
    STRUCT(0134, 'Kanto', 'Vaporeon', 'Water' , NULL),
    STRUCT(0135, 'Kanto', 'Jolteon', 'Electric' , NULL),
    STRUCT(0136, 'Kanto', 'Flareon', 'Fire' , NULL),
    STRUCT(0137, 'Kanto', 'Porygon', 'Normal' , NULL),
    STRUCT(0138, 'Kanto', 'Omanyte', 'Rock' , 'Water'),
    STRUCT(0139, 'Kanto', 'Omastar', 'Rock' , 'Water'),

    STRUCT(0140, 'Kanto', 'Kabuto', 'Rock' , 'Water'),
    STRUCT(0141, 'Kanto', 'Kabutops', 'Rock' , 'Water'),
    STRUCT(0142, 'Kanto', 'Aerodactyl', 'Rock' , 'Flying'),
    STRUCT(0143, 'Kanto', 'Snorlax', 'Normal' , NULL),
    STRUCT(0144, 'Kanto', 'Articuno', 'Ice' , 'Flying'),
    STRUCT(0145, 'Kanto', 'Zapdos', 'Electric' , 'Flying'),
    STRUCT(0146, 'Kanto', 'Moltres', 'Fire' , 'Flying'),
    STRUCT(0147, 'Kanto', 'Dratini', 'Dragon' , NULL),
    STRUCT(0148, 'Kanto', 'Dragonair', 'Dragon' , NULL),
    STRUCT(0149, 'Kanto', 'Dragonite', 'Dragon' , 'Flying'),

    STRUCT(0150, 'Kanto', 'Mewtwo', 'Psychic' , NULL),
    STRUCT(0151, 'Kanto', 'Mew', 'Psychic' , NULL),

    --Johto Region

    STRUCT(0152, 'Jooto', 'Chikorita', 'Grass' , NULL),
    STRUCT(0153, 'Johto', 'Bayleaf', 'Grass' , NULL),
    STRUCT(0154, 'Johto', 'Meganium', 'Grass' , NULL),
    STRUCT(0155, 'Johto', 'Cyndaquil', 'Fire' , NULL),
    STRUCT(0156, 'Johto', 'Quilava', 'Fire' , NULL),
    STRUCT(0157, 'Johto', 'Typhlosion', 'Fire' , NULL),
    STRUCT(0158, 'Johto', 'Totodile', 'Water' , NULL),
    STRUCT(0159, 'Johto', 'Croconaw', 'Water' , NULL),

    STRUCT(0160, 'Johto', 'Feraligatr', 'Water' , NULL),
    STRUCT(0161, 'Johto', 'Sentret', 'Normal' , NULL),
    STRUCT(0162, 'Johto', 'Furret', 'Normal' , NULL),
    STRUCT(0163, 'Johto', 'Hoothoot', 'Normal' , 'Flying'),
    STRUCT(0164, 'Johto', 'Noctowl', 'Normal' , 'Flying'),
    STRUCT(0165, 'Johto', 'Ledyba', 'Bug' , 'Flying'),
    STRUCT(0166, 'Johto', 'Ledian', 'Bug' , 'Flying'),
    STRUCT(0167, 'Johto', 'Spinarak', 'Bug' , 'Poison'),
    STRUCT(0168, 'Johto', 'Ariados', 'Bug' , 'Poison'),
    STRUCT(0169, 'Johto', 'Crobat', 'Poison' , 'Flying'),

    STRUCT(0170, 'Johto', 'Chinchou', 'Water' , 'Electric'),
    STRUCT(0171, 'Johto', 'Lanturn', 'Water' , 'Electric'),
    STRUCT(0172, 'Johto', 'Pichu', 'Electric' , NULL),
    STRUCT(0173, 'Johto', 'Cleffa', 'Fairy' , NULL),
    STRUCT(0174, 'Johto', 'Igglybuff', 'Normal' , 'Fairy'),
    STRUCT(0175, 'Johto', 'Togepi', 'Fairy' , NULL),
    STRUCT(0176, 'Johto', 'Togetic', 'Fairy' , 'Flying'),
    STRUCT(0177, 'Johto', 'Natu', 'Psychic' , 'Flying'),
    STRUCT(0178, 'Johto', 'Xatu', 'Psychic' , 'Flying'),
    STRUCT(0179, 'Johto', 'Mareep', 'Electric' , NULL),

    STRUCT(0180, 'Johto', 'Flaaffy', 'Electric' , NULL),
    STRUCT(0181, 'Johto', 'Ampharos', 'Electric' , NULL),
    STRUCT(0182, 'Johto', 'Bellossom', 'Grass' , NULL),
    STRUCT(0183, 'Johto', 'Marill', 'Water' , 'Fairy'),
    STRUCT(0184, 'Johto', 'Azumarill', 'Water' , 'Fairy'),
    STRUCT(0185, 'Johto', 'Sudowoodo', 'Rock',NULL ),
    STRUCT(0186, 'Johto', 'Politoed', 'Water',NULL ),
    STRUCT(0187, 'Johto', 'Hoppip', 'Grass','Flying' ),
    STRUCT(0188, 'Johto', 'Skiploom', 'Grass','Flying' ),
    STRUCT(0189, 'Johto', 'Jumpluff', 'Grass','Flying' ),

    STRUCT(0190, 'Johto', 'Aipom', 'Normal', NULL ),
    STRUCT(0191, 'Johto', 'Sunkern', 'Grass', NULL ),
    STRUCT(0192, 'Johto', 'Sunflora', 'Grass', NULL),
    STRUCT(0193, 'Johto', 'Yanma', 'Bug','Flying' ),
    STRUCT(0194, 'Johto', 'Wooper', 'Water','Ground' ),
    STRUCT(0195, 'Johto', 'Quagsire', 'Water','Ground' ),
    STRUCT(0196, 'Johto', 'Espeon', 'Psychic',Null ),
    STRUCT(0197, 'Johto', 'Umbreon', 'Dark',NULL ),
    STRUCT(0198, 'Johto', 'Murkrow', 'Dark','Flying' ),
    STRUCT(0199, 'Johto', 'Slowking', 'Water','Psychic' ),

    STRUCT(0200, 'Johto', 'Misdreavus', 'Ghost', NULL ),
    STRUCT(0201, 'Johto', 'Unown', 'Psychic',NULL ),
    STRUCT(0202, 'Johto', 'Wobbuffet', 'Psychic', NULL ),
    STRUCT(0203, 'Johto', 'Girafarig', 'Normal','Psychic' ),
    STRUCT(0204, 'Johto', 'Pineco', 'Bug', NULL ),
    STRUCT(0205, 'Johto', 'Forretress', 'Bug','Steel' ),
    STRUCT(0206, 'Johto', 'Dunsparce', 'Normal',Null ),
    STRUCT(0207, 'Johto', 'Gligar', 'Ground','Flying' ),
    STRUCT(0208, 'Johto', 'Steelix', 'Steel','Ground' ),
    STRUCT(0209, 'Johto', 'Snubbull', 'Fairy',NULL ),

    STRUCT(0210, 'Johto', 'Granbull', 'Fairy',NULL ),
    STRUCT(0211, 'Johto', 'Qwilfish', 'Water','Poison' ),
    STRUCT(0212, 'Johto', 'Scizor', 'Bug','Steel' ),
    STRUCT(0213, 'Johto', 'Shuckle', 'Bug','Rock' ),
    STRUCT(0214, 'Johto', 'Heracross', 'Bug','Fighting' ),
    STRUCT(0215, 'Johto', 'Sneasel', 'Dark','Ice' ),
    STRUCT(0216, 'Johto', 'Teddiursa', 'Normal',NULL ),
    STRUCT(0217, 'Johto', 'Ursaring', 'Normal',NULL ),
    STRUCT(0218, 'Johto', 'Slugma', 'Fire',NULL ),
    STRUCT(0219, 'Johto', 'Magcargo', 'Fire','Rock' ),

    STRUCT(0220, 'Johto', 'Swinub', 'Ice','Ground' ),
    STRUCT(0221, 'Johto', 'Piloswine', 'Ice','Ground' ),
    STRUCT(0222, 'Johto', 'Corsola', 'Water','Rock' ),
    STRUCT(0223, 'Johto', 'Remoraid', 'Water',NULL ),
    STRUCT(0224, 'Johto', 'Octillery', 'Water',NULL ),
    STRUCT(0225, 'Johto', 'Delibird', 'Ice','Flying' ),
    STRUCT(0226, 'Johto', 'Mantine', 'Water','Flying' ),
    STRUCT(0227, 'Johto', 'Skarmory', 'Steel', 'Flying'),
    STRUCT(0228, 'Johto', 'Houndour', 'Dark', 'Fire'),
    STRUCT(0229, 'Johto', 'Houndoom', 'Dark', 'Fire'),

    STRUCT(0230, 'Johto', 'Kingdra', 'Water', 'Dragon'),
    STRUCT(0231, 'Johto', 'Phanpy', 'Ground', NULL),
    STRUCT(0232, 'Johto', 'Donphan', 'Ground', NULL),
    STRUCT(0233, 'Johto', 'Porygon2', 'Normal',NULL ),
    STRUCT(0234, 'Johto', 'Stantler', 'Normal', NULL),
    STRUCT(0235, 'Johto', 'Smeargle', 'Normal', NULL),
    STRUCT(0236, 'Johto', 'Tyrogue', 'Fighting', NULL),
    STRUCT(0237, 'Johto', 'Hitmontop', 'Fighting', NULL),
    STRUCT(0238, 'Johto', 'Smoochum', 'Ice', 'Psychic'),
    STRUCT(0239, 'Johto', 'Elekid', 'Electric', NULL),

    STRUCT(0240, 'Johto', 'Magby', 'Fire', NULL ),
    STRUCT(0241, 'Johto', 'Miltank', 'Normal', NULL),
    STRUCT(0242, 'Johto', 'Blissey', 'Normal', NULL),
    STRUCT(0243, 'Johto', 'Raikou', 'Electric', NULL),
    STRUCT(0244, 'Johto', 'Entei', 'Fire', NULL),
    STRUCT(0245, 'Johto', 'Suicune', 'Water', NULL),
    STRUCT(0246, 'Johto', 'Larvitar', 'Rock', 'Ground'),
    STRUCT(0247, 'Johto', 'Pupitar', 'Rock', 'Ground'),
    STRUCT(0248, 'Johto', 'Tyranitar', 'Rock', 'Dark'),
    STRUCT(0249, 'Johto', 'Lugia', 'Psychic', 'Flying'),

    STRUCT(0250, 'Johto', 'Ho-Oh', 'Fire', 'Flying'),
    STRUCT(0251, 'Johto', 'Celebi', 'Psychic', 'Grass'),

    --Hoenn Region

    STRUCT(0252, 'Hoenn', 'Treecko', 'Grass', NULL),
    STRUCT(0253, 'Hoenn', 'Grovyle', 'Grass', NULL),
    STRUCT(0254, 'Hoenn', 'Sceptile', 'Grass', NULL),
    STRUCT(0255, 'Hoenn', 'Torchic', 'Fire', NULL),
    STRUCT(0256, 'Hoenn', 'Combusken', 'Fire', 'Fighting'),
    STRUCT(0257, 'Hoenn', 'Blaziken', 'Fire', 'Fighting'),
    STRUCT(0258, 'Hoenn', 'Mudkip', 'Water', NULL),
    STRUCT(0259, 'Hoenn', 'Marshtomp', 'Water', 'Ground'),

    STRUCT(0260, 'Hoenn', 'Swampert', 'Water', 'Ground'),
    STRUCT(0261, 'Hoenn', 'Poochyena', 'Dark', NULL),
    STRUCT(0262, 'Hoenn', 'Mightyena', 'Dark', NULL),
    STRUCT(0263, 'Hoenn', 'Zigzagoon', 'Normal', NULL),
    STRUCT(0264, 'Hoenn', 'Linoone', 'Normal', NULL),
    STRUCT(0265, 'Hoenn', 'Wurmple', 'Bug', NULL),
    STRUCT(0266, 'Hoenn', 'Silcoon', 'Bug', NULL),
    STRUCT(0267, 'Hoenn', 'Beautifly', 'Bug', 'Flying'),
    STRUCT(0268, 'Hoenn', 'Cascoon', 'Bug', NULL),
    STRUCT(0269, 'Hoenn', 'Dustox', 'Bug', 'Poison'),

    STRUCT(0270, 'Hoenn', 'Lotad', 'Water', 'Grass'),
    STRUCT(0271, 'Hoenn', 'Lombre', 'Water', 'Grass'),
    STRUCT(0272, 'Hoenn', 'Ludicolo', 'Water', 'Grass'),
    STRUCT(0273, 'Hoenn', 'Seedot', 'Grass', NULL),
    STRUCT(0274, 'Hoenn', 'Nuzleaf', 'Grass', 'Dark'),
    STRUCT(0275, 'Hoenn', 'Shiftry', 'Grass', 'Dark'),
    STRUCT(0276, 'Hoenn', 'Taillow', 'Normal', 'Flying'),
    STRUCT(0277, 'Hoenn', 'Swellow', 'Normal', 'Flying'),
    STRUCT(0278, 'Hoenn', 'Wingull', 'Water', 'Flying'),
    STRUCT(0279, 'Hoenn', 'Pelipper', 'Water', 'Flying'),

    STRUCT(0280, 'Hoenn', 'Ralts', 'Psychic', 'Fairy'),
    STRUCT(0281, 'Hoenn', 'Kirlia', 'Psychic', 'Fairy'),
    STRUCT(0282, 'Hoenn', 'Gardevoir', 'Psychic', 'Fairy'),
    STRUCT(0283, 'Hoenn', 'Surskit', 'Bug', 'Water'),
    STRUCT(0284, 'Hoenn', 'Masquerain', 'Bug', 'Flying'),
    STRUCT(0285, 'Hoenn', 'Shroomish', 'Grass', NULL),
    STRUCT(0286, 'Hoenn', 'Breloom', 'Grass', 'Fighting'),
    STRUCT(0287, 'Hoenn', 'Slakoth', 'Normal', NULL),
    STRUCT(0288, 'Hoenn', 'Vigoroth', 'Normal', NULL),
    STRUCT(0289, 'Hoenn', 'Slaking', 'Normal', NULL),

    STRUCT(0290, 'Hoenn', 'Nincada', 'Bug', 'Ground'),
    STRUCT(0291, 'Hoenn', 'Ninjask', 'Bug', 'Flying'),
    STRUCT(0292, 'Hoenn', 'Shedinja', 'Bug', 'Ghost'),
    STRUCT(0293, 'Hoenn', 'Whismur', 'Normal', NULL),
    STRUCT(0294, 'Hoenn', 'Loudred', 'Normal', NULL),
    STRUCT(0295, 'Hoenn', 'Exploud', 'Normal', NULL),
    STRUCT(0296, 'Hoenn', 'Makuhita', 'Fighting', NULL),
    STRUCT(0297, 'Hoenn', 'Hariyama', 'Fighting', NULL),
    STRUCT(0298, 'Hoenn', 'Azurill', 'Normal', 'Fairy'),
    STRUCT(0299, 'Hoenn', 'Nosepass', 'Rock', NULL),

    STRUCT(0300, 'Hoenn', 'Skitty', 'Normal', NULL),
    STRUCT(0301, 'Hoenn', 'Delcatty', 'Normal', NULL),
    STRUCT(0302, 'Hoenn', 'Sableye', 'Dark', 'Ghost'),
    STRUCT(0303, 'Hoenn', 'Mawile', 'Steel', 'Fairy'),
    STRUCT(0304, 'Hoenn', 'Aron', 'Steel', 'Rock'),
    STRUCT(0305, 'Hoenn', 'Lairon', 'Steel', 'Rock'),
    STRUCT(0306, 'Hoenn', 'Aggron', 'Steel', 'Rock'),
    STRUCT(0307, 'Hoenn', 'Meditite', 'Fighting', 'Psychic'),
    STRUCT(0308, 'Hoenn', 'Medicham', 'Fighting', 'Psychic'),
    STRUCT(0309, 'Hoenn', 'Electrike', 'Electric', NULL),

    STRUCT(0310, 'Hoenn', 'Manectric', 'Electric', NULL),
    STRUCT(0311, 'Hoenn', 'Plusle', 'Electric', NULL),
    STRUCT(0312, 'Hoenn', 'Minun', 'Electric', NULL),
    STRUCT(0313, 'Hoenn', 'Volbeat', 'Bug', NULL),
    STRUCT(0314, 'Hoenn', 'Illumise', 'Bug', NULL),
    STRUCT(0315, 'Hoenn', 'Roselia', 'Grass', 'Poison'),
    STRUCT(0316, 'Hoenn', 'Gulpin', 'Poison', NULL),
    STRUCT(0317, 'Hoenn', 'Swalot', 'Poison', NULL),
    STRUCT(0318, 'Hoenn', 'Carvanha', 'Water', 'Dark'),
    STRUCT(0319, 'Hoenn', 'Sharpedo', 'Water', 'Dark'),

    STRUCT(0320, 'Hoenn', 'Wailmer', 'Water', NULL),
    STRUCT(0321, 'Hoenn', 'Wailord', 'Water', NULL),
    STRUCT(0322, 'Hoenn', 'Numel', 'Fire', 'Ground'),
    STRUCT(0323, 'Hoenn', 'Camerupt', 'Fire', 'Ground'),
    STRUCT(0324, 'Hoenn', 'Torkoal', 'Fire', NULL),
    STRUCT(0325, 'Hoenn', 'Spoink', 'Psychic', NULL),
    STRUCT(0326, 'Hoenn', 'Grumpig', 'Psychic', NULL),
    STRUCT(0327, 'Hoenn', 'Spinda', 'Normal', NULL),
    STRUCT(0328, 'Hoenn', 'Trapinch', 'Ground', NULL),
    STRUCT(0329, 'Hoenn', 'Vibrava', 'Ground', 'Dragon'),

    STRUCT(0330, 'Hoenn', 'Flygon', 'Ground', 'Dragon'),
    STRUCT(0331, 'Hoenn', 'Cacnea', 'Grass', NULL),
    STRUCT(0332, 'Hoenn', 'Cacturne', 'Grass', 'Dark'),
    STRUCT(0333, 'Hoenn', 'Swablu', 'Normal', 'Flying'),
    STRUCT(0334, 'Hoenn', 'Altaria', 'Dragon', 'Flying'),
    STRUCT(0335, 'Hoenn', 'Zangoose', 'Normal', NULL),
    STRUCT(0336, 'Hoenn', 'Seviper', 'Poison', NULL),
    STRUCT(0337, 'Hoenn', 'Lunatone', 'Rock', 'Psychic'),
    STRUCT(0338, 'Hoenn', 'Solrock', 'Rock', 'Psychic'),
    STRUCT(0339, 'Hoenn', 'Barboach', 'Water', 'Ground'),

    STRUCT(0340, 'Hoenn', 'Whiscash', 'Water', 'Ground'),
    STRUCT(0341, 'Hoenn', 'Corphish', 'Water', NULL),
    STRUCT(0342, 'Hoenn', 'Crawdaunt', 'Water', 'Dark'),
    STRUCT(0343, 'Hoenn', 'Baltoy', 'Ground', 'Psychic'),
    STRUCT(0344, 'Hoenn', 'Claydol', 'Ground', 'Psychic'),
    STRUCT(0345, 'Hoenn', 'Lileep', 'Rock', 'Grass'),
    STRUCT(0346, 'Hoenn', 'Cradily', 'Rock', 'Grass'),
    STRUCT(0347, 'Hoenn', 'Anorith', 'Rock', 'Bug'),
    STRUCT(0348, 'Hoenn', 'Armaldo', 'Rock', 'Bug'),
    STRUCT(0349, 'Hoenn', 'Feebas', 'Water', NULL),

    STRUCT(0350, 'Hoenn', 'Milotic', 'Water', NULL),
    STRUCT(0351, 'Hoenn', 'Castform', 'Normal', NULL),
    STRUCT(0352, 'Hoenn', 'Kecleon', 'Normal', NULL),
    STRUCT(0353, 'Hoenn', 'Shuppet', 'Ghost', NULL),
    STRUCT(0354, 'Hoenn', 'Banette', 'Ghost', NULL),
    STRUCT(0355, 'Hoenn', 'Duskull', 'Ghost', NULL),
    STRUCT(0356, 'Hoenn', 'Dusclops', 'Ghost', NULL),
    STRUCT(0357, 'Hoenn', 'Tropius', 'Grass', 'Flying'),
    STRUCT(0358, 'Hoenn', 'Chimecho', 'Psychic', NULL),
    STRUCT(0359, 'Hoenn', 'Absol', 'Dark', NULL),

    STRUCT(0360, 'Hoenn', 'Wynaut', 'Psychic', NULL),
    STRUCT(0361, 'Hoenn', 'Snorunt', 'Ice', NULL),
    STRUCT(0362, 'Hoenn', 'Glalie', 'Ice', NULL),
    STRUCT(0363, 'Hoenn', 'Spheal', 'Ice', 'Water'),
    STRUCT(0364, 'Hoenn', 'Sealeo', 'Ice', 'Water'),
    STRUCT(0365, 'Hoenn', 'Walrein', 'Ice', 'Water'),
    STRUCT(0366, 'Hoenn', 'Clamperl', 'Water', NULL),
    STRUCT(0367, 'Hoenn', 'Huntail', 'Water', NULL),
    STRUCT(0368, 'Hoenn', 'Gorebyss', 'Water', NULL),
    STRUCT(0369, 'Hoenn', 'Relicanth', 'Water', 'Rock'),

    STRUCT(0370, 'Hoenn', 'Luvdisc', 'Water', NULL),
    STRUCT(0371, 'Hoenn', 'Bagon', 'Dragon', NULL),
    STRUCT(0372, 'Hoenn', 'Shelgon', 'Dragon', NULL),
    STRUCT(0373, 'Hoenn', 'Salamence', 'Dragon', 'Flying'),
    STRUCT(0374, 'Hoenn', 'Beldum', 'Steel', 'Psychic'),
    STRUCT(0375, 'Hoenn', 'Metang', 'Steel', 'Psychic'),
    STRUCT(0376, 'Hoenn', 'Metagross', 'Steel', 'Psychic'),
    STRUCT(0377, 'Hoenn', 'Regirock', 'Rock', NULL),
    STRUCT(0378, 'Hoenn', 'Regice', 'Ice', NULL),
    STRUCT(0379, 'Hoenn', 'Registeel', 'Steel', NULL),
    
    STRUCT(0380, 'Hoenn', 'Latias', 'Dragon', 'Psychic'),
    STRUCT(0381, 'Hoenn', 'Latios', 'Dragon', 'Psychic'),
    STRUCT(0382, 'Hoenn', 'Kyogre', 'Water', NULL),
    STRUCT(0383, 'Hoenn', 'Groudon', 'Ground', NULL),
    STRUCT(0384, 'Hoenn', 'Rayquaza', 'Dragon', 'Flying'),
    STRUCT(0385, 'Hoenn', 'Jirachi', 'Steel', 'Psychic'),
    STRUCT(0386, 'Hoenn', 'Deoxys', 'Psychic', NULL)
  ])
) AS source
ON target.pokedex_number = source.pokedex_number
AND target.pokemon_region = source.pokemon_region

WHEN NOT MATCHED THEN
INSERt(
  pokedex_number, pokemon_region, pokemon_species, primary_type, secondary_type
)
VALUES(
  source.pokedex_number, source.pokemon_region, source.pokemon_species,source.primary_type, source.secondary_type
);
