-- =============================================
-- SEEDING DIM SPECIES LIST
-- Sinnoh, Unova, Kalos, Alola Regions
-- There are two pokemon with unknown regions
-- =============================================


MERGE `pokemon-corporate-registry.pogo_corp.dim_species` target
USING ( 
  SELECT * FROM UNNEST ([
    --SINNOH REGION
    STRUCT(0389 AS pokedex_number, 'Sinnoh' AS pokemon_region, 'Torterra' AS pokemon_species, 'Grass' AS primary_type, 'Ground' AS secondary_type),
    STRUCT(0387, 'Sinnoh', 'Turtwig', 'Grass', NULL),
    STRUCT(0388, 'Sinnoh', 'Grotle', 'Grass', NULL),
    

    STRUCT(0390, 'Sinnoh', 'Chimchar', 'Fire', NULL),
    STRUCT(0391, 'Sinnoh', 'Monferno', 'Fire', 'Fighting'),
    STRUCT(0392, 'Sinnoh', 'Infernape', 'Fire', 'Fighting'),
    STRUCT(0393, 'Sinnoh', 'Piplup', 'Water', NULL),
    STRUCT(0394, 'Sinnoh', 'Prinplup', 'Water', NULL),
    STRUCT(0395, 'Sinnoh', 'Empoleon', 'Water', 'Steel'),
    STRUCT(0396, 'Sinnoh', 'Starly', 'Normal', 'Flying'),
    STRUCT(0397, 'Sinnoh', 'Staravia', 'Normal', 'Flying'),
    STRUCT(0398, 'Sinnoh', 'Staraptor', 'Normal', 'Flying'),
    STRUCT(0399, 'Sinnoh', 'Bidoof', 'Normal', NULL),

    STRUCT(0400, 'Sinnoh', 'Bibarel', 'Normal', 'Water'),
    STRUCT(0401, 'Sinnoh', 'Kricketot', 'Bug', NULL),
    STRUCT(0402, 'Sinnoh', 'Kricketune', 'Bug', NULL),
    STRUCT(0403, 'Sinnoh', 'Shinx', 'Electric', NULL),
    STRUCT(0404, 'Sinnoh', 'Luxio', 'Electric', NULL),
    STRUCT(0405, 'Sinnoh', 'Luxray', 'Electric', NULL),
    STRUCT(0406, 'Sinnoh', 'Budew', 'Grass', 'Poison'),
    STRUCT(0407, 'Sinnoh', 'Roserade', 'Grass', 'Poison'),
    STRUCT(0408, 'Sinnoh', 'Cranidos', 'Rock', NULL),
    STRUCT(0409, 'Sinnoh', 'Rampardos', 'Rock', NULL),

    STRUCT(0410, 'Sinnoh', 'Shieldon', 'Rock', 'Steel'),
    STRUCT(0411, 'Sinnoh', 'Bastiodon', 'Rock', 'Steel'),
    STRUCT(0412, 'Sinnoh', 'Burmy', 'Bug', NULL),
    STRUCT(0413, 'Sinnoh', 'Wormadam', 'Bug', 'Grass'),
    STRUCT(0414, 'Sinnoh', 'Mothim', 'Bug', 'Flying'),
    STRUCT(0415, 'Sinnoh', 'Combee', 'Bug', 'Flying'),
    STRUCT(0416, 'Sinnoh', 'Vespiquen', 'Bug', 'Flying'),
    STRUCT(0417, 'Sinnoh', 'Pachirisu', 'Electric', NULL),
    STRUCT(0418, 'Sinnoh', 'Buizel', 'Water', NULL),
    STRUCT(0419, 'Sinnoh', 'Floatzel', 'Water', NULL),

    STRUCT(0420, 'Sinnoh', 'Cherubi', 'Grass', NULL),
    STRUCT(0421, 'Sinnoh', 'Cherrim', 'Grass', NULL),
    STRUCT(0422, 'Sinnoh', 'Shellos', 'Water', NULL),
    STRUCT(0423, 'Sinnoh', 'Gastrodon', 'Water', 'Ground'),
    STRUCT(0424, 'Sinnoh', 'Ambipom', 'Normal', NULL),
    STRUCT(0425, 'Sinnoh', 'Drifloon', 'Ghost', 'Flying'),
    STRUCT(0426, 'Sinnoh', 'Drifblim', 'Ghost', 'Flying'),
    STRUCT(0427, 'Sinnoh', 'Buneary', 'Normal', NULL),
    STRUCT(0428, 'Sinnoh', 'Lopunny', 'Normal', NULL),
    STRUCT(0429, 'Sinnoh', 'Mismagius', 'Ghost', NULL),

    STRUCT(0430, 'Sinnoh', 'Honchkrow', 'Dark', 'Flying'),
    STRUCT(0431, 'Sinnoh', 'Glameow', 'Normal', NULL),
    STRUCT(0432, 'Sinnoh', 'Purugly', 'Normal', NULL),
    STRUCT(0433, 'Sinnoh', 'Chingling', 'Psychic', NULL),
    STRUCT(0434, 'Sinnoh', 'Stunky', 'Poison', 'Dark'),
    STRUCT(0435, 'Sinnoh', 'Skuntank', 'Poison', 'Dark'),
    STRUCT(0436, 'Sinnoh', 'Bronzor', 'Steel', 'Psychic'),
    STRUCT(0437, 'Sinnoh', 'Bronzong', 'Steel', 'Psychic'),
    STRUCT(0438, 'Sinnoh', 'Bonsly', 'Rock', NULL),
    STRUCT(0439, 'Sinnoh', "Mime Jr.", 'Psychic', 'Fairy'),

    STRUCT(0440, 'Sinnoh', 'Happiny', 'Normal', NULL),
    STRUCT(0441, 'Sinnoh', 'Chatot', 'Normal', 'Flying'),
    STRUCT(0442, 'Sinnoh', 'Spiritomb', 'Ghost', 'Dark'),
    STRUCT(0443, 'Sinnoh', 'Gible', 'Dragon', 'Ground'),
    STRUCT(0444, 'Sinnoh', 'Gabite', 'Dragon', 'Ground'),
    STRUCT(0445, 'Sinnoh', 'Garchomp', 'Dragon', 'Ground'),
    STRUCT(0446, 'Sinnoh', 'Munchlax', 'Normal', NULL),
    STRUCT(0447, 'Sinnoh', 'Riolu', 'Fighting', NULL),
    STRUCT(0448, 'Sinnoh', 'Lucario', 'Fighting', 'Steel'),
    STRUCT(0449, 'Sinnoh', 'Hippopotas', 'Ground', NULL),

    STRUCT(0450, 'Sinnoh', 'Hippowdon', 'Ground', NULL),
    STRUCT(0451, 'Sinnoh', 'Skorupi', 'Poison', 'Bug'),
    STRUCT(0452, 'Sinnoh', 'Drapion', 'Poison', 'Dark'),
    STRUCT(0453, 'Sinnoh', 'Croagunk', 'Poison', 'Fighting'),
    STRUCT(0454, 'Sinnoh', 'Toxicroak', 'Poison', 'Fighting'),
    STRUCT(0455, 'Sinnoh', 'Carnivine', 'Grass', NULL),
    STRUCT(0456, 'Sinnoh', 'Finneon', 'Water', NULL),
    STRUCT(0457, 'Sinnoh', 'Lumineon', 'Water', NULL),
    STRUCT(0458, 'Sinnoh', 'Mantyke', 'Water', 'Flying'),
    STRUCT(0459, 'Sinnoh', 'Snover', 'Grass', 'Ice'),

    STRUCT(0460, 'Sinnoh', 'Abomasnow', 'Grass', 'Ice'),
    STRUCT(0461, 'Sinnoh', 'Weavile', 'Dark', 'Ice'),
    STRUCT(0462, 'Sinnoh', 'Magnezone', 'Electric', 'Steel'),
    STRUCT(0463, 'Sinnoh', 'Lickilicky', 'Normal', NULL),
    STRUCT(0464, 'Sinnoh', 'Rhyperior', 'Ground', 'Rock'),
    STRUCT(0465, 'Sinnoh', 'Tangrowth', 'Grass', NULL),
    STRUCT(0466, 'Sinnoh', 'Electivire', 'Electric', NULL),
    STRUCT(0467, 'Sinnoh', 'Magmortar', 'Fire', NULL),
    STRUCT(0468, 'Sinnoh', 'Togekiss', 'Fairy', 'Flying'),
    STRUCT(0469, 'Sinnoh', 'Yanmega', 'Bug', 'Flying'),

    STRUCT(0470, 'Sinnoh', 'Leafeon', 'Grass', NULL),
    STRUCT(0471, 'Sinnoh', 'Glaceon', 'Ice', NULL),
    STRUCT(0472, 'Sinnoh', 'Gliscor', 'Ground', 'Flying'),
    STRUCT(0473, 'Sinnoh', 'Mamoswine', 'Ice', 'Ground'),
    STRUCT(0474, 'Sinnoh', "Porygon-Z", 'Normal', NULL),
    STRUCT(0475, 'Sinnoh', 'Gallade', 'Psychic', 'Fighting'),
    STRUCT(0476, 'Sinnoh', 'Probopass', 'Rock', 'Steel'),
    STRUCT(0477, 'Sinnoh', 'Dusknoir', 'Ghost', NULL),
    STRUCT(0478, 'Sinnoh', 'Froslass', 'Ice', 'Ghost'),
    STRUCT(0479, 'Sinnoh', 'Rotom', 'Electric', 'Ghost'),

    STRUCT(0480, 'Sinnoh', 'Uxie', 'Psychic', NULL),
    STRUCT(0481, 'Sinnoh', 'Mesprit', 'Psychic', NULL),
    STRUCT(0482, 'Sinnoh', 'Azelf', 'Psychic', NULL),
    STRUCT(0483, 'Sinnoh', 'Dialga', 'Steel', 'Dragon'),
    STRUCT(0484, 'Sinnoh', 'Palkia', 'Water', 'Dragon'),
    STRUCT(0485, 'Sinnoh', 'Heatran', 'Fire', 'Steel'),
    STRUCT(0486, 'Sinnoh', 'Regigigas', 'Normal', NULL),
    STRUCT(0487, 'Sinnoh', 'Giratina', 'Ghost', 'Dragon'),
    STRUCT(0488, 'Sinnoh', 'Cresselia', 'Psychic', NULL),
    STRUCT(0489, 'Sinnoh', 'Phione', 'Water', NULL),

    STRUCT(0490, 'Sinnoh', 'Manaphy', 'Water', NULL),
    STRUCT(0491, 'Sinnoh', 'Darkrai', 'Dark', NULL),
    STRUCT(0492, 'Sinnoh', 'Shaymin', 'Grass', NULL),
    STRUCT(0493, 'Sinnoh', 'Arceus', 'Normal', NULL),



    --UNOVA REGION    
    STRUCT(0494, 'Unova', 'Victini', 'Psychic', 'Fire'),
    STRUCT(0495, 'Unova', 'Snivy', 'Grass', NULL),
    STRUCT(0496, 'Unova', 'Servine', 'Grass', NULL),
    STRUCT(0497, 'Unova', 'Serperior', 'Grass', NULL),
    STRUCT(0498, 'Unova', 'Tepig', 'Fire', NULL),
    STRUCT(0499, 'Unova', 'Pignite', 'Fire', 'Fighting'),

    STRUCT(0500, 'Unova', 'Emboar', 'Fire', 'Fighting'),
    STRUCT(0501, 'Unova', 'Oshawott', 'Water', NULL),
    STRUCT(0502, 'Unova', 'Dewott', 'Water', NULL),
    STRUCT(0503, 'Unova', 'Samurott', 'Water', NULL),
    STRUCT(0504, 'Unova', 'Patrat', 'Normal', NULL),
    STRUCT(0505, 'Unova', 'Watchog', 'Normal', NULL),
    STRUCT(0506, 'Unova', 'Lillipup', 'Normal', NULL),
    STRUCT(0507, 'Unova', 'Herdier', 'Normal', NULL),
    STRUCT(0508, 'Unova', 'Stoutland', 'Normal', NULL),
    STRUCT(0509, 'Unova', 'Purrloin', 'Dark', NULL),

    STRUCT(0510, 'Unova', 'Liepard', 'Dark', NULL),
    STRUCT(0511, 'Unova', 'Pansage', 'Grass', NUll),
    STRUCT(0512, 'Unova', 'Simisage', 'Grass', NULL),
    STRUCT(0513, 'Unova', 'Pansear', 'Fire', NULL),
    STRUCT(0514, 'Unova', 'Simisear', 'Fire', NULL),
    STRUCT(0515, 'Unova', 'Panpour', 'Water', NULL),
    STRUCT(0516, 'Unova', 'Simipour', 'Water', NULL),
    STRUCT(0517, 'Unova', 'Munna', 'Psychic', NULL),
    STRUCT(0518, 'Unova', 'Musharna', 'Psychic', NULL),
    STRUCT(0519, 'Unova', 'Pidove', 'Normal', 'Flying'),

    STRUCT(0520, 'Unova', 'Tranquill', 'Normal', 'Flying'),
    STRUCT(0521, 'Unova', 'Unfezant', 'Normal', 'Flying'),
    STRUCT(0522, 'Unova', 'Blitzle', 'Electric', NULL),
    STRUCT(0523, 'Unova', 'Zebstrika', 'Electric', NULL),
    STRUCT(0524, 'Unova', 'Roggenrola', 'Rock', NULL),
    STRUCT(0525, 'Unova', 'Boldore', 'Rock', NULL),
    STRUCT(0526, 'Unova', 'Gigalith', 'Rock', NULL),
    STRUCT(0527, 'Unova', 'Woobat', 'Psychic', 'Flying'),
    STRUCT(0528, 'Unova', 'Swoobat', 'Psychic', 'Flying'),
    STRUCT(0529, 'Unova', 'Drilbur', 'Ground', NULL),

    STRUCT(0530, 'Unova', 'Excadrill', 'Ground', 'Steel'),
    STRUCT(0531, 'Unova', 'Audino', 'Normal', NULL),
    STRUCT(0532, 'Unova', 'Timburr', 'Fighting', NULL),
    STRUCT(0533, 'Unova', 'Gurdurr', 'Fighting', NULL),
    STRUCT(0534, 'Unova', 'Conkeldurr', 'Fighting', NULL),
    STRUCT(0535, 'Unova', 'Tympole', 'Water', NULL),
    STRUCT(0536, 'Unova', 'Palpitoad', 'Water', 'Ground'),
    STRUCT(0537, 'Unova', 'Seismitoad', 'Water', 'Ground'),
    STRUCT(0538, 'Unova', 'Throh', 'Fighting', NULL),
    STRUCT(0539, 'Unova', 'Sawk', 'Fighting', NULL),

    STRUCT(0540, 'Unova', 'Sewaddle', 'Bug', 'Grass'),
    STRUCT(0541, 'Unova', 'Swadloon', 'Bug', 'Grass'),
    STRUCT(0542, 'Unova', 'Leavanny', 'Bug', 'Grass'),
    STRUCT(0543, 'Unova', 'Venipede', 'Bug', 'Poison'),
    STRUCT(0544, 'Unova', 'Whirlipede', 'Bug', 'Poison'),
    STRUCT(0545, 'Unova', 'Scolipede', 'Bug', 'Poison'),
    STRUCT(0546, 'Unova', 'Cottonee', 'Grass', 'Fairy'),
    STRUCT(0547, 'Unova', 'Whimsicott', 'Grass', 'Fairy'),
    STRUCT(0548, 'Unova', 'Petilil', 'Grass', NULL),
    STRUCT(0549, 'Unova', 'Lilligant', 'Grass', NULL),

    STRUCT(0550, 'Unova', 'Basculin', 'Water', NULL),
    STRUCT(0551, 'Unova', 'Sandile', 'Ground', 'Dark'),
    STRUCT(0552, 'Unova', 'Krokorok', 'Ground', 'Dark'),
    STRUCT(0553, 'Unova', 'Krookodile', 'Ground', 'Dark'),
    STRUCT(0554, 'Unova', 'Darumaka', 'Fire', NULL),
    STRUCT(0555, 'Unova', 'Darmanitan', 'Fire', NULL),
    STRUCT(0556, 'Unova', 'Maractus', 'Grass', NULL),
    STRUCT(0557, 'Unova', 'Dwebble', 'Bug', 'Rock'),
    STRUCT(0558, 'Unova', 'Crustle', 'Bug', 'Rock'),
    STRUCT(0559, 'Unova', 'Scraggy', 'Dark', 'Fighting'),

    STRUCT(0560, 'Unova', 'Scrafty', 'Dark', 'Fighting'),
    STRUCT(0561, 'Unova', 'Sigilyph', 'Psychic', 'Flying'),
    STRUCT(0562, 'Unova', 'Yamask', 'Ghost', NULL),
    STRUCT(0563, 'Unova', 'Cofagrigus', 'Ghost', NULL),
    STRUCT(0564, 'Unova', 'Tirtouga', 'Water', 'Rock'),
    STRUCT(0565, 'Unova', 'Carracosta', 'Water', 'Rock'),
    STRUCT(0566, 'Unova', 'Archen', 'Rock', 'Flying'),
    STRUCT(0567, 'Unova', 'Archeops', 'Rock', 'Flying'),
    STRUCT(0568, 'Unova', 'Trubbish', 'Poison', NULL),
    STRUCT(0569, 'Unova', 'Garbodor', 'Poison', NULL),

    STRUCT(0570, 'Unova', 'Zorua', 'Dark', NULL),
    STRUCT(0571, 'Unova', 'Zoroark', 'Dark', NULL),
    STRUCT(0572, 'Unova', 'Minccino', 'Normal', NULL),
    STRUCT(0573, 'Unova', 'Cinccino', 'Normal', NULL),
    STRUCT(0574, 'Unova', 'Gothita', 'Psychic', NULL),
    STRUCT(0575, 'Unova', 'Gothorita', 'Psychic', NULL),
    STRUCT(0576, 'Unova', 'Gothitelle', 'Psychic', NULL),
    STRUCT(0577, 'Unova', 'Solosis', 'Psychic', NULL),
    STRUCT(0578, 'Unova', 'Duosion', 'Psychic', NULL),
    STRUCT(0579, 'Unova', 'Reuniclus', 'Psychic', NULL),

    STRUCT(0580, 'Unova', 'Ducklett', 'Water', 'Flying'),
    STRUCT(0581, 'Unova', 'Swanna', 'Water', 'Flying'),
    STRUCT(0582, 'Unova', 'Vanillite', 'Ice', NULL),
    STRUCT(0583, 'Unova', 'Vanillish', 'Ice', NULL),
    STRUCT(0584, 'Unova', 'Vanilluxe', 'Ice', NULL),
    STRUCT(0585, 'Unova', 'Deerling', 'Normal', 'Grass'),
    STRUCT(0586, 'Unova', 'Sawsbuck', 'Normal', 'Grass'),
    STRUCT(0587, 'Unova', 'Emolga', 'Electric', 'Flying'),
    STRUCT(0588, 'Unova', 'Karrablast', 'Bug', NULL),
    STRUCT(0589, 'Unova', 'Escavalier', 'Bug', 'Steel'),

    STRUCT(0590, 'Unova', 'Foongus', 'Grass', 'Poison'),
    STRUCT(0591, 'Unova', 'Amoonguss', 'Grass', 'Poison'),
    STRUCT(0592, 'Unova', 'Frillish', 'Water', 'Ghost'),
    STRUCT(0593, 'Unova', 'Jellicent', 'Water', 'Ghost'),
    STRUCT(0594, 'Unova', 'Alomomola', 'Water', NULL),
    STRUCT(0595, 'Unova', 'Joltik', 'Bug', 'Electric'),
    STRUCT(0596, 'Unova', 'Galvantula', 'Bug', 'Electric'),
    STRUCT(0597, 'Unova', 'Ferroseed', 'Grass', 'Steel'),
    STRUCT(0598, 'Unova', 'Ferrothorn', 'Grass', 'Steel'),
    STRUCT(0599, 'Unova', 'Klink', 'Steel', NULL),

    STRUCT(0600, 'Unova', 'Klang', 'Steel', NULL),
    STRUCT(0601, 'Unova', 'Klinklang', 'Steel', NULL),
    STRUCT(0602, 'Unova', 'Tynamo', 'Electric', NULL),
    STRUCT(0603, 'Unova', 'Eelektrik', 'Electric', NULL),
    STRUCT(0604, 'Unova', 'Eelektross', 'Electric', NULL),
    STRUCT(0605, 'Unova', 'Elgyem', 'Psychic', NULL),
    STRUCT(0606, 'Unova', 'Beheeyem', 'Psychic', NULL),
    STRUCT(0607, 'Unova', 'Litwick', 'Ghost', 'Fire'),
    STRUCT(0608, 'Unova', 'Lampent', 'Ghost', 'Fire'),
    STRUCT(0609, 'Unova', 'Chandelure', 'Ghost', 'Fire'),

    STRUCT(0610, 'Unova', 'Axew', 'Dragon', NULL),
    STRUCT(0611, 'Unova', 'Fraxure', 'Dragon', NULL),
    STRUCT(0612, 'Unova', 'Haxorus', 'Dragon', NULL),
    STRUCT(0613, 'Unova', 'Cubchoo', 'Ice', NULL),
    STRUCT(0614, 'Unova', 'Beartic', 'Ice', NULL),
    STRUCT(0615, 'Unova', 'Cryogonal', 'Ice', NULL),
    STRUCT(0616, 'Unova', 'Shelmet', 'Bug', NULL),
    STRUCT(0617, 'Unova', 'Accelgor', 'Bug', NULL),
    STRUCT(0618, 'Unova', 'Stunfisk', 'Ground', 'Electric'),
    STRUCT(0619, 'Unova', 'Mienfoo', 'Fighting', NULL),

    STRUCT(0620, 'Unova', 'Mienshao', 'Fighting', NULL),
    STRUCT(0621, 'Unova', 'Druddigon', 'Dragon', NULL),
    STRUCT(0622, 'Unova', 'Golett', 'Ground', 'Ghost'),
    STRUCT(0623, 'Unova', 'Golurk', 'Ground', 'Ghost'),
    STRUCT(0624, 'Unova', 'Pawniard', 'Dark', 'Steel'),
    STRUCT(0625, 'Unova', 'Bisharp', 'Dark', 'Steel'),
    STRUCT(0626, 'Unova', 'Bouffalant', 'Normal', NULL),
    STRUCT(0627, 'Unova', 'Rufflet', 'Normal', 'Flying'),
    STRUCT(0628, 'Unova', 'Braviary', 'Normal', 'Flying'),
    STRUCT(0629, 'Unova', 'Vullaby', 'Dark', 'Flying'),

    STRUCT(0630, 'Unova', 'Mandibuzz', 'Dark', 'Flying'),
    STRUCT(0631, 'Unova', 'Heatmor', 'Fire', NULL),
    STRUCT(0632, 'Unova', 'Durant', 'Bug', 'Steel'),
    STRUCT(0633, 'Unova', 'Deino', 'Dark', 'Dragon'),
    STRUCT(0634, 'Unova', 'Zweilous', 'Dark', 'Dragon'),
    STRUCT(0635, 'Unova', 'Hydreigon', 'Dark', 'Dragon'),
    STRUCT(0636, 'Unova', 'Larvesta', 'Bug', 'Fire'),
    STRUCT(0637, 'Unova', 'Volcarona', 'Bug', 'Fire'),
    STRUCT(0638, 'Unova', 'Cobalion', 'Steel', 'Fighting'),
    STRUCT(0639, 'Unova', 'Terrakion', 'Rock', 'Fighting'),

    STRUCT(0640, 'Unova', 'Virizion', 'Grass', 'Fighting'),
    STRUCT(0641, 'Unova', 'Tornadus', 'Flying', NULL),
    STRUCT(0642, 'Unova', 'Thundurus', 'Electric', 'Flying'),
    STRUCT(0643, 'Unova', 'Reshiram', 'Dragon', 'Fire'),
    STRUCT(0644, 'Unova', 'Zekrom', 'Dragon', 'Electric'),
    STRUCT(0645, 'Unova', 'Landorus', 'Ground', 'Flying'),
    STRUCT(0646, 'Unova', 'Kyurem', 'Dragon', 'Ice'),
    STRUCT(0647, 'Unova', 'Keldeo', 'Water', 'Fighting'),
    STRUCT(0648, 'Unova', 'Meloetta', 'Normal', 'Psychic'),
    STRUCT(0649, 'Unova', 'Genesect', 'Bug', 'Steel'),



    --KALOS REGION
    STRUCT(0650, 'Kalos', 'Chespin', 'Grass', NULL),
    STRUCT(0651, 'Kalos', 'Quilladin', 'Grass', NULL),
    STRUCT(0652, 'Kalos', 'Chesnaught', 'Grass', 'Fighting'),
    STRUCT(0653, 'Kalos', 'Fennekin', 'Fire', NULL),
    STRUCT(0654, 'Kalos', 'Braixen', 'Fire', NULL),
    STRUCT(0655, 'Kalos', 'Delphox', 'Fire', 'Psychic'),
    STRUCT(0656, 'Kalos', 'Froakie', 'Water', NULL),
    STRUCT(0657, 'Kalos', 'Frogadier', 'Water', NULL),
    STRUCT(0658, 'Kalos', 'Greninja', 'Water', 'Dark'),
    STRUCT(0659, 'Kalos', 'Bunnelby', 'Normal', NULL),

    STRUCT(0660, 'Kalos', 'Diggersby', 'Normal', 'Ground'),
    STRUCT(0661, 'Kalos', 'Fletchling', 'Normal', 'Flying'),
    STRUCT(0662, 'Kalos', 'Fletchinder', 'Fire', 'Flying'),
    STRUCT(0663, 'Kalos', 'Talonflame', 'Fire', 'Flying'),
    STRUCT(0664, 'Kalos', 'Scatterbug', 'Bug', NULL),
    STRUCT(0665, 'Kalos', 'Spewpa', 'Bug', NULL),
    STRUCT(0666, 'Kalos', 'Vivillon', 'Bug', 'Flying'),
    STRUCT(0667, 'Kalos', 'Litleo', 'Fire', 'Normal'),
    STRUCT(0668, 'Kalos', 'Pyroar', 'Fire', 'Normal'),
    STRUCT(0669, 'Kalos', 'Flabebe', 'Fairy', NULL),
    
    STRUCT(0670, 'Kalos', 'Floette', 'Fairy', NULL),
    STRUCT(0671, 'Kalos', 'Florges', 'Fairy', NULL),
    STRUCT(0672, 'Kalos', 'Skiddo', 'Grass', NULL),
    STRUCT(0673, 'Kalos', 'Gogoat', 'Grass', NULL),
    STRUCT(0674, 'Kalos', 'Pancham', 'Fighting', NULL),
    STRUCT(0675, 'Kalos', 'Pangoro', 'Fighting', 'Dark'),
    STRUCT(0676, 'Kalos', 'Furfrou', 'Normal', NULL),
    STRUCT(0677, 'Kalos', 'Espurr', 'Psychic', NULL),
    STRUCT(0678, 'Kalos', 'Meowstic', 'Psychic', NULL),
    STRUCT(0679, 'Kalos', 'Honedge', 'Steel', 'Ghost'),

    STRUCT(0680, 'Kalos', 'Doublade', 'Steel', 'Ghost'),
    STRUCT(0681, 'Kalos', 'Aegislash', 'Steel', 'Ghost'),
    STRUCT(0682, 'Kalos', 'Spritzee', 'Fairy', NULL),
    STRUCT(0683, 'Kalos', 'Aromatisse', 'Fairy', NULL),
    STRUCT(0684, 'Kalos', 'Swirlix', 'Fairy', NULL),
    STRUCT(0685, 'Kalos', 'Slurpuff', 'Fairy', NULL),
    STRUCT(0686, 'Kalos', 'Inkay', 'Dark', 'Psychic'),
    STRUCT(0687, 'Kalos', 'Malamar', 'Dark', 'Psychic'),
    STRUCT(0688, 'Kalos', 'Binacle', 'Rock', 'Water'),
    STRUCT(0689, 'Kalos', 'Barbaracle', 'Rock', 'Water'),

    STRUCT(0690, 'Kalos', 'Skrelp', 'Poison', 'Water'),
    STRUCT(0691, 'Kalos', 'Dragalge', 'Poison', 'Dragon'),
    STRUCT(0692, 'Kalos', 'Clauncher', 'Water', NULL),
    STRUCT(0693, 'Kalos', 'Clawitzer', 'Water', NULL),
    STRUCT(0694, 'Kalos', 'Helioptile', 'Electric', 'Normal'),
    STRUCT(0695, 'Kalos', 'Heliolisk', 'Electric', 'Normal'),
    STRUCT(0696, 'Kalos', 'Tyrunt', 'Rock', 'Dragon'),
    STRUCT(0697, 'Kalos', 'Tyrantrum', 'Rock', 'Dragon'),
    STRUCT(0698, 'Kalos', 'Amaura', 'Rock', 'Ice'),
    STRUCT(0699, 'Kalos', 'Aurorus', 'Rock', 'Ice'),

    STRUCT(0700, 'Kalos', 'Sylveon', 'Fairy', NULL),
    STRUCT(0701, 'Kalos', 'Hawlucha', 'Fighting', 'Flying'),
    STRUCT(0702, 'Kalos', 'Dedenne', 'Electric', 'Fairy'),
    STRUCT(0703, 'Kalos', 'Carbink', 'Rock', 'Fairy'),
    STRUCT(0704, 'Kalos', 'Goomy', 'Dragon', NULL),
    STRUCT(0705, 'Kalos', 'Sliggoo', 'Dragon', NULL),
    STRUCT(0706, 'Kalos', 'Goodra', 'Dragon', NULL),
    STRUCT(0707, 'Kalos', 'Klefki', 'Steel', 'Fairy'),
    STRUCT(0708, 'Kalos', 'Phantump', 'Ghost', 'Grass'),
    STRUCT(0709, 'Kalos', 'Trevenant', 'Ghost', 'Grass'),

    STRUCT(0710, 'Kalos', 'Pumpkaboo', 'Ghost', 'Grass'),
    STRUCT(0711, 'Kalos', 'Gourgeist', 'Ghost', 'Grass'),
    STRUCT(0712, 'Kalos', 'Bergmite', 'Ice', NULL),
    STRUCT(0713, 'Kalos', 'Avalugg', 'Ice', NULL),
    STRUCT(0714, 'Kalos', 'Noibat', 'Flying', 'Dragon'),
    STRUCT(0715, 'Kalos', 'Noivern', 'Flying', 'Dragon'),
    STRUCT(0716, 'Kalos', 'Xerneas', 'Fairy', NULL),
    STRUCT(0717, 'Kalos', 'Yveltal', 'Dark', 'Flying'),
    STRUCT(0718, 'Kalos', 'Zygarde', 'Dragon', 'Ground'),
    STRUCT(0719, 'Kalos', 'Diancie', 'Rock', 'Fairy'),

    STRUCT(0720, 'Kalos', 'Hoopa', 'Psychic', 'Ghost'),
    STRUCT(0721, 'Kalos', 'Volcanion', 'Fire', 'Water'),



    --ALOLA REGION
    STRUCT(0722, 'Alola', 'Rowlet', 'Grass', 'Flying'),
    STRUCT(0723, 'Alola', 'Dartrix', 'Grass', 'Flying'),
    STRUCT(0724, 'Alola', 'Decidueye', 'Grass', 'Ghost'),
    STRUCT(0725, 'Alola', 'Litten', 'Fire', NULL),
    STRUCT(0726, 'Alola', 'Torracat', 'Fire', NULL),
    STRUCT(0727, 'Alola', 'Incineroar', 'Fire', 'Dark'),
    STRUCT(0728, 'Alola', 'Popplio', 'Water', NULL),
    STRUCT(0729, 'Alola', 'Brionne', 'Water', NULL),

    STRUCT(0730, 'Alola', 'Primarina', 'Water', 'Fairy'),
    STRUCT(0731, 'Alola', 'Pikipek', 'Normal', 'Flying'),
    STRUCT(0732, 'Alola', 'Trumbeak', 'Normal', 'Flying'),
    STRUCT(0733, 'Alola', 'Toucannon', 'Normal', 'Flying'),
    STRUCT(0734, 'Alola', 'Yungoos', 'Normal', NULL),
    STRUCT(0735, 'Alola', 'Gumshoos', 'Normal', NULL),
    STRUCT(0736, 'Alola', 'Grubbin', 'Bug', NULL),
    STRUCT(0737, 'Alola', 'Charjabug', 'Bug', 'Electric'),
    STRUCT(0738, 'Alola', 'Vikavolt', 'Bug', 'Electric'),
    STRUCT(0739, 'Alola', 'Crabrawler', 'Fighting', NULL),

    STRUCT(0740, 'Alola', 'Crabominable', 'Fighting', 'Ice'),
    STRUCT(0741, 'Alola', 'Oricorio', 'Fire', 'Flying'),
    STRUCT(0742, 'Alola', 'Cutiefly', 'Bug', 'Fairy'),
    STRUCT(0743, 'Alola', 'Ribombee', 'Bug', 'Fairy'),
    STRUCT(0744, 'Alola', 'Rockruff', 'Rock', NULL),
    STRUCT(0745, 'Alola', 'Lycanroc', 'Rock', NULL),
    STRUCT(0746, 'Alola', 'Wishiwashi', 'Water', NULL),
    STRUCT(0747, 'Alola', 'Mareanie', 'Poison', 'Water'),
    STRUCT(0748, 'Alola', 'Toxapex', 'Poison', 'Water'),
    STRUCT(0749, 'Alola', 'Mudbray', 'Ground', NULL),

    STRUCT(0750, 'Alola', 'Mudsdale', 'Ground', NULL),
    STRUCT(0751, 'Alola', 'Dewpider', 'Water', 'Bug'),
    STRUCT(0752, 'Alola', 'Araquanid', 'Water', 'Bug'),
    STRUCT(0753, 'Alola', 'Fomantis', 'Grass', NULL),
    STRUCT(0754, 'Alola', 'Lurantis', 'Grass', NULL),
    STRUCT(0755, 'Alola', 'Morelull', 'Grass', 'Fairy'),
    STRUCT(0756, 'Alola', 'Shiinotic', 'Grass', 'Fairy'),
    STRUCT(0757, 'Alola', 'Salandit', 'Poison', 'Fire'),
    STRUCT(0758, 'Alola', 'Salazzle', 'Poison','Fire' ),
    STRUCT(0759, 'Alola', 'Stufful', 'Normal', 'Fighting'),

    STRUCT(0760, 'Alola', 'Bewear', 'Normal', 'Fighting'),
    STRUCT(0761, 'Alola', 'Bounsweet', 'Grass', NULL),
    STRUCT(0762, 'Alola', 'Steenee', 'Grass', NULL),
    STRUCT(0763, 'Alola', 'Tsareena', 'Grass', NULL),
    STRUCT(0764, 'Alola', 'Comfey', 'Fairy', NULL),
    STRUCT(0765, 'Alola', 'Oranguru', 'Normal', 'Psychic'),
    STRUCT(0766, 'Alola', 'Passimian', 'Fighting', 'Dragon'),
    STRUCT(0767, 'Alola', 'Wimpod', 'Bug', 'Water'),
    STRUCT(0768, 'Alola', 'Golisopod', 'Bug', 'Water'),
    STRUCT(0769, 'Alola', 'Sandygast', 'Ghost', 'Ground'),

    STRUCT(0770, 'Alola', 'Palossand', 'Ghost', 'Ground'),
    STRUCT(0771, 'Alola', 'Pyukumuku', 'Water', NULL),
    STRUCT(0772, 'Alola', "Type: Null", 'Normal', NULL),
    STRUCT(0773, 'Alola', 'Silvally', 'Normal', NULL),
    STRUCT(0774, 'Alola', 'Minior', 'Rock', 'Flying'),
    STRUCT(0775, 'Alola', 'Komala', 'Normal', NULL),
    STRUCT(0776, 'Alola', 'Turtonator', 'Fire', 'Dragon'),
    STRUCT(0777, 'Alola', 'Togedemaru', 'Electric', 'Steel'),
    STRUCT(0778, 'Alola', 'Mimikyu', 'Ghost', 'Fairy'),
    STRUCT(0779, 'Alola', 'Bruxish', 'Water', 'Psychic'),

    STRUCT(0780, 'Alola', 'Drampa', 'Normal', 'Dragon'),
    STRUCT(0781, 'Alola', 'Dhelmise', 'Ghost', 'Grass'),
    STRUCT(0782, 'Alola', "Jangmo-o", 'Dragon', NULL),
    STRUCT(0783, 'Alola', "Hakamo-o", 'Dragon', 'Fighting'),
    STRUCT(0784, 'Alola', "Kommo-o", 'Dragon', 'Fighting'),
    STRUCT(0785, 'Alola', 'Tapu Koko', 'Electric', 'Fairy'),
    STRUCT(0786, 'Alola', 'Tapu Lele', 'Psychic', 'Fairy'),
    STRUCT(0787, 'Alola', 'Tapu Bulu', 'Grass', 'Fairy'),
    STRUCT(0788, 'Alola', 'Tapu Fini', 'Water', 'Fairy'),
    STRUCT(0789, 'Alola', 'Cosmog', 'Psychic', NULL),
    
    STRUCT(0790, 'Alola', 'Cosmoem', 'Psychic', NULL),
    STRUCT(0791, 'Alola', 'Solgaleo', 'Psychic', 'Steel'),
    STRUCT(0792, 'Alola', 'Lunala', 'Psychic', 'Ghost'),
    STRUCT(0793, 'Alola', 'Nihilego', 'Rock', 'Poison'),
    STRUCT(0794, 'Alola', 'Buzzwole', 'Bug', 'Fighting'),
    STRUCT(0795, 'Alola', 'Pheromosa', 'Bug', 'Fighting'),
    STRUCT(0796, 'Alola', 'Xurkitree', 'Electric', NULL),
    STRUCT(0797, 'Alola', 'Celesteela', 'Steel', 'Flying'),
    STRUCT(0798, 'Alola', 'Kartana', 'Grass', 'Steel'),
    STRUCT(0799, 'Alola', 'Guzzlord', 'Dark', 'Dragon'),

    STRUCT(0800, 'Alola', 'Necrozma', 'Psychic', NULL),
    STRUCT(0801, 'Alola', 'Magearna', 'Steel', 'Fairy'),
    STRUCT(0802, 'Alola', 'Marshadow', 'Fighting', 'Ghost'),
    STRUCT(0803, 'Alola', 'Poipole', 'Poison', NULL),
    STRUCT(0804, 'Alola', 'Naganadel', 'Poison','Dragon'),
    STRUCT(0805, 'Alola', 'Stakataka', 'Rock', 'Steel'),
    STRUCT(0806, 'Alola', 'Blacephalon', 'Fire', 'Ghost'),
    STRUCT(0807, 'Alola', 'Zeraora', 'Electric', NULL),


    --UNIDENTIFIED
    STRUCT(0808, 'Unidentified', 'Meltan', 'Steel', NULL),
    STRUCT(0809, 'Unidentified', 'Melmetal', 'Steel', NULL)



  ])

) AS source
ON target.pokedex_number = source.pokedex_number
AND target.pokemon_region = source.pokemon_region

WHEN NOT MATCHED THEN
INSERt(
  pokedex_number, pokemon_region, pokemon_species, primary_type, secondary_type
)
VALUES(
  source.pokedex_number, source.pokemon_region, source.pokemon_species,source.primary_type, source.secondary_type
);

